#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtk3
Version  : 3.24.36
Release  : 113
URL      : https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.36.tar.xz
Source0  : https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.36.tar.xz
Source1  : icon-cache-update-trigger.service
Summary  : GTK+ Unix print support
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: gtk3-bin = %{version}-%{release}
Requires: gtk3-data = %{version}-%{release}
Requires: gtk3-filemap = %{version}-%{release}
Requires: gtk3-lib = %{version}-%{release}
Requires: gtk3-license = %{version}-%{release}
Requires: gtk3-locales = %{version}-%{release}
Requires: gtk3-services = %{version}-%{release}
Requires: gsettings-desktop-schemas
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : colord-dev
BuildRequires : cups-dev
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : fribidi-dev
BuildRequires : gobject-introspection-dev
BuildRequires : ibus
BuildRequires : ibus-dev
BuildRequires : ibus-libpinyin
BuildRequires : krb5-dev
BuildRequires : libXcursor-dev
BuildRequires : libXinerama-dev
BuildRequires : libinput-dev
BuildRequires : libxkbcommon-dev
BuildRequires : libxml2-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(atk-bridge-2.0)
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
BuildRequires : sassc
BuildRequires : wayland-dev
BuildRequires : wayland-protocols-dev
BuildRequires : xorgproto-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: segfault.patch
Patch2: madvise.patch
Patch3: ignore-cache-datestamp.patch
Patch4: no-gerror.patch
Patch5: add-icon-cache-update-script.patch
Patch6: expand-search-for-icon-theme.cache.patch

%description
Summary
-------
* Do not edit the CSS directly, edit the source SCSS files
* To be able to use the latest/adequate version of SASS, install sassc
* The configure script will detect whether or not you have sassc installed;
if you do, it will regenerate the CSS every time you modify the SCSS files
and rebuild GTK+.

%package bin
Summary: bin components for the gtk3 package.
Group: Binaries
Requires: gtk3-data = %{version}-%{release}
Requires: gtk3-license = %{version}-%{release}
Requires: gtk3-services = %{version}-%{release}
Requires: gtk3-filemap = %{version}-%{release}

%description bin
bin components for the gtk3 package.


%package data
Summary: data components for the gtk3 package.
Group: Data

%description data
data components for the gtk3 package.


%package dev
Summary: dev components for the gtk3 package.
Group: Development
Requires: gtk3-lib = %{version}-%{release}
Requires: gtk3-bin = %{version}-%{release}
Requires: gtk3-data = %{version}-%{release}
Provides: gtk3-devel = %{version}-%{release}
Requires: gtk3 = %{version}-%{release}

%description dev
dev components for the gtk3 package.


%package filemap
Summary: filemap components for the gtk3 package.
Group: Default

%description filemap
filemap components for the gtk3 package.


%package lib
Summary: lib components for the gtk3 package.
Group: Libraries
Requires: gtk3-data = %{version}-%{release}
Requires: gtk3-license = %{version}-%{release}
Requires: gtk3-filemap = %{version}-%{release}

%description lib
lib components for the gtk3 package.


%package license
Summary: license components for the gtk3 package.
Group: Default

%description license
license components for the gtk3 package.


%package locales
Summary: locales components for the gtk3 package.
Group: Default

%description locales
locales components for the gtk3 package.


%package services
Summary: services components for the gtk3 package.
Group: Systemd services

%description services
services components for the gtk3 package.


%prep
%setup -q -n gtk+-3.24.36
cd %{_builddir}/gtk+-3.24.36
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
pushd ..
cp -a gtk+-3.24.36 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1676474683
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gtk3
cp %{_builddir}/gtk+-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gtk3/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/gtk+-%{version}/gdk/COPYING %{buildroot}/usr/share/package-licenses/gtk3/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gtk30-properties
%find_lang gtk30
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/icon-cache-update-trigger.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants
ln -s /usr/lib/systemd/system/icon-cache-update-trigger.service %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/icon-cache-update-trigger.service
install -m 0755 icon-cache-update.sh %{buildroot}/usr/bin

mkdir -p %{buildroot}/usr/lib64/gtk-3.0/3.0.0/
%{buildroot}/usr/bin/gtk-query-immodules-3.0 > %{buildroot}/usr/lib64/gtk-3.0/3.0.0/immodules.cache
sed -i -e "s/.*Created by.*//g"  %{buildroot}/usr/lib64/gtk-3.0/3.0.0/immodules.cache
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/gtk-3.0/3.0.0/immodules.cache

%files bin
%defattr(-,root,root,-)
/usr/bin/gtk-builder-tool
/usr/bin/gtk-encode-symbolic-svg
/usr/bin/gtk-launch
/usr/bin/gtk-query-immodules-3.0
/usr/bin/gtk-query-settings
/usr/bin/gtk-update-icon-cache
/usr/bin/gtk3-demo
/usr/bin/gtk3-demo-application
/usr/bin/gtk3-icon-browser
/usr/bin/gtk3-widget-factory
/usr/bin/icon-cache-update.sh
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gdk-3.0.typelib
/usr/lib64/girepository-1.0/GdkX11-3.0.typelib
/usr/lib64/girepository-1.0/Gtk-3.0.typelib
/usr/share/applications/gtk3-demo.desktop
/usr/share/applications/gtk3-icon-browser.desktop
/usr/share/applications/gtk3-widget-factory.desktop
/usr/share/gettext/its/gtkbuilder.its
/usr/share/gettext/its/gtkbuilder.loc
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gtk.Demo.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.ColorChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.EmojiChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.exampleapp.gschema.xml
/usr/share/gtk-3.0/emoji/de.gresource
/usr/share/gtk-3.0/emoji/es.gresource
/usr/share/gtk-3.0/emoji/fr.gresource
/usr/share/gtk-3.0/emoji/zh.gresource
/usr/share/gtk-3.0/gtkbuilder.rng
/usr/share/gtk-3.0/valgrind/gtk.supp
/usr/share/icons/hicolor/16x16/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/16x16/apps/gtk3-demo.png
/usr/share/icons/hicolor/16x16/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/16x16/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/22x22/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/22x22/apps/gtk3-demo.png
/usr/share/icons/hicolor/22x22/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/22x22/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/24x24/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/24x24/apps/gtk3-demo.png
/usr/share/icons/hicolor/24x24/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/24x24/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/256x256/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/256x256/apps/gtk3-demo.png
/usr/share/icons/hicolor/256x256/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/256x256/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/32x32/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/32x32/apps/gtk3-demo.png
/usr/share/icons/hicolor/32x32/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/32x32/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/48x48/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/48x48/apps/gtk3-demo.png
/usr/share/icons/hicolor/48x48/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/48x48/apps/gtk3-widget-factory.png
/usr/share/themes/Default/gtk-3.0/gtk-keys.css
/usr/share/themes/Emacs/gtk-3.0/gtk-keys.css

%files dev
%defattr(-,root,root,-)
/usr/include/gail-3.0/libgail-util/gail-util.h
/usr/include/gail-3.0/libgail-util/gailmisc.h
/usr/include/gail-3.0/libgail-util/gailtextutil.h
/usr/include/gtk-3.0/gdk/deprecated/gdkcolor.h
/usr/include/gtk-3.0/gdk/gdk-autocleanup.h
/usr/include/gtk-3.0/gdk/gdk.h
/usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h
/usr/include/gtk-3.0/gdk/gdkcairo.h
/usr/include/gtk-3.0/gdk/gdkconfig.h
/usr/include/gtk-3.0/gdk/gdkcursor.h
/usr/include/gtk-3.0/gdk/gdkdevice.h
/usr/include/gtk-3.0/gdk/gdkdevicemanager.h
/usr/include/gtk-3.0/gdk/gdkdevicepad.h
/usr/include/gtk-3.0/gdk/gdkdevicetool.h
/usr/include/gtk-3.0/gdk/gdkdisplay.h
/usr/include/gtk-3.0/gdk/gdkdisplaymanager.h
/usr/include/gtk-3.0/gdk/gdkdnd.h
/usr/include/gtk-3.0/gdk/gdkdrawingcontext.h
/usr/include/gtk-3.0/gdk/gdkenumtypes.h
/usr/include/gtk-3.0/gdk/gdkevents.h
/usr/include/gtk-3.0/gdk/gdkframeclock.h
/usr/include/gtk-3.0/gdk/gdkframetimings.h
/usr/include/gtk-3.0/gdk/gdkglcontext.h
/usr/include/gtk-3.0/gdk/gdkkeys.h
/usr/include/gtk-3.0/gdk/gdkkeysyms-compat.h
/usr/include/gtk-3.0/gdk/gdkkeysyms.h
/usr/include/gtk-3.0/gdk/gdkmain.h
/usr/include/gtk-3.0/gdk/gdkmonitor.h
/usr/include/gtk-3.0/gdk/gdkpango.h
/usr/include/gtk-3.0/gdk/gdkpixbuf.h
/usr/include/gtk-3.0/gdk/gdkprivate.h
/usr/include/gtk-3.0/gdk/gdkproperty.h
/usr/include/gtk-3.0/gdk/gdkrectangle.h
/usr/include/gtk-3.0/gdk/gdkrgba.h
/usr/include/gtk-3.0/gdk/gdkscreen.h
/usr/include/gtk-3.0/gdk/gdkseat.h
/usr/include/gtk-3.0/gdk/gdkselection.h
/usr/include/gtk-3.0/gdk/gdktestutils.h
/usr/include/gtk-3.0/gdk/gdkthreads.h
/usr/include/gtk-3.0/gdk/gdktypes.h
/usr/include/gtk-3.0/gdk/gdkversionmacros.h
/usr/include/gtk-3.0/gdk/gdkvisual.h
/usr/include/gtk-3.0/gdk/gdkwayland.h
/usr/include/gtk-3.0/gdk/gdkwindow.h
/usr/include/gtk-3.0/gdk/gdkx.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylanddevice.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylanddisplay.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandglcontext.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandmonitor.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandselection.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandwindow.h
/usr/include/gtk-3.0/gdk/x11/gdkx-autocleanups.h
/usr/include/gtk-3.0/gdk/x11/gdkx11applaunchcontext.h
/usr/include/gtk-3.0/gdk/x11/gdkx11cursor.h
/usr/include/gtk-3.0/gdk/x11/gdkx11device-core.h
/usr/include/gtk-3.0/gdk/x11/gdkx11device-xi2.h
/usr/include/gtk-3.0/gdk/x11/gdkx11device.h
/usr/include/gtk-3.0/gdk/x11/gdkx11devicemanager-core.h
/usr/include/gtk-3.0/gdk/x11/gdkx11devicemanager-xi2.h
/usr/include/gtk-3.0/gdk/x11/gdkx11devicemanager.h
/usr/include/gtk-3.0/gdk/x11/gdkx11display.h
/usr/include/gtk-3.0/gdk/x11/gdkx11displaymanager.h
/usr/include/gtk-3.0/gdk/x11/gdkx11dnd.h
/usr/include/gtk-3.0/gdk/x11/gdkx11glcontext.h
/usr/include/gtk-3.0/gdk/x11/gdkx11keys.h
/usr/include/gtk-3.0/gdk/x11/gdkx11monitor.h
/usr/include/gtk-3.0/gdk/x11/gdkx11property.h
/usr/include/gtk-3.0/gdk/x11/gdkx11screen.h
/usr/include/gtk-3.0/gdk/x11/gdkx11selection.h
/usr/include/gtk-3.0/gdk/x11/gdkx11utils.h
/usr/include/gtk-3.0/gdk/x11/gdkx11visual.h
/usr/include/gtk-3.0/gdk/x11/gdkx11window.h
/usr/include/gtk-3.0/gtk/a11y/gtk-a11y-autocleanups.h
/usr/include/gtk-3.0/gtk/a11y/gtkarrowaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkbooleancellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcellaccessibleparent.h
/usr/include/gtk-3.0/gtk/a11y/gtkcheckmenuitemaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcomboboxaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcontaineraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcontainercellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkentryaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkexpanderaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkfilechooserwidgetaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkflowboxaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkflowboxchildaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkframeaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkheaderbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkiconviewaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkimageaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkimagecellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklabelaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklevelbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklinkbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklistboxaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklistboxrowaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklockbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenuaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenubuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenuitemaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenushellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtknotebookaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtknotebookpageaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkpanedaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkplugaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkpopoveraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkprogressbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkradiobuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkradiomenuitemaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkrangeaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkrenderercellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkscaleaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkscalebuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkscrolledwindowaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtksocketaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkspinbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkspinneraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkstackaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkstatusbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkswitchaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktextcellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktextviewaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktogglebuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktoplevelaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktreeviewaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkwidgetaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkwindowaccessible.h
/usr/include/gtk-3.0/gtk/deprecated/gtkaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h
/usr/include/gtk-3.0/gtk/deprecated/gtkactivatable.h
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h
/usr/include/gtk-3.0/gtk/deprecated/gtkarrow.h
/usr/include/gtk-3.0/gtk/deprecated/gtkcolorsel.h
/usr/include/gtk-3.0/gtk/deprecated/gtkcolorseldialog.h
/usr/include/gtk-3.0/gtk/deprecated/gtkfontsel.h
/usr/include/gtk-3.0/gtk/deprecated/gtkgradient.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhandlebox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhbbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhpaned.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhscale.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhscrollbar.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhseparator.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhsv.h
/usr/include/gtk-3.0/gtk/deprecated/gtkiconfactory.h
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h
/usr/include/gtk-3.0/gtk/deprecated/gtkmisc.h
/usr/include/gtk-3.0/gtk/deprecated/gtknumerableicon.h
/usr/include/gtk-3.0/gtk/deprecated/gtkradioaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkrc.h
/usr/include/gtk-3.0/gtk/deprecated/gtkrecentaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstock.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstyle.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstyleproperties.h
/usr/include/gtk-3.0/gtk/deprecated/gtksymboliccolor.h
/usr/include/gtk-3.0/gtk/deprecated/gtktable.h
/usr/include/gtk-3.0/gtk/deprecated/gtktearoffmenuitem.h
/usr/include/gtk-3.0/gtk/deprecated/gtkthemingengine.h
/usr/include/gtk-3.0/gtk/deprecated/gtktoggleaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkuimanager.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvbbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvpaned.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvscale.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvscrollbar.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvseparator.h
/usr/include/gtk-3.0/gtk/gtk-a11y.h
/usr/include/gtk-3.0/gtk/gtk-autocleanups.h
/usr/include/gtk-3.0/gtk/gtk.h
/usr/include/gtk-3.0/gtk/gtkaboutdialog.h
/usr/include/gtk-3.0/gtk/gtkaccelgroup.h
/usr/include/gtk-3.0/gtk/gtkaccellabel.h
/usr/include/gtk-3.0/gtk/gtkaccelmap.h
/usr/include/gtk-3.0/gtk/gtkaccessible.h
/usr/include/gtk-3.0/gtk/gtkactionable.h
/usr/include/gtk-3.0/gtk/gtkactionbar.h
/usr/include/gtk-3.0/gtk/gtkadjustment.h
/usr/include/gtk-3.0/gtk/gtkappchooser.h
/usr/include/gtk-3.0/gtk/gtkappchooserbutton.h
/usr/include/gtk-3.0/gtk/gtkappchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkappchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkapplication.h
/usr/include/gtk-3.0/gtk/gtkapplicationwindow.h
/usr/include/gtk-3.0/gtk/gtkaspectframe.h
/usr/include/gtk-3.0/gtk/gtkassistant.h
/usr/include/gtk-3.0/gtk/gtkbbox.h
/usr/include/gtk-3.0/gtk/gtkbin.h
/usr/include/gtk-3.0/gtk/gtkbindings.h
/usr/include/gtk-3.0/gtk/gtkborder.h
/usr/include/gtk-3.0/gtk/gtkbox.h
/usr/include/gtk-3.0/gtk/gtkbuildable.h
/usr/include/gtk-3.0/gtk/gtkbuilder.h
/usr/include/gtk-3.0/gtk/gtkbutton.h
/usr/include/gtk-3.0/gtk/gtkcalendar.h
/usr/include/gtk-3.0/gtk/gtkcellarea.h
/usr/include/gtk-3.0/gtk/gtkcellareabox.h
/usr/include/gtk-3.0/gtk/gtkcellareacontext.h
/usr/include/gtk-3.0/gtk/gtkcelleditable.h
/usr/include/gtk-3.0/gtk/gtkcelllayout.h
/usr/include/gtk-3.0/gtk/gtkcellrenderer.h
/usr/include/gtk-3.0/gtk/gtkcellrendereraccel.h
/usr/include/gtk-3.0/gtk/gtkcellrenderercombo.h
/usr/include/gtk-3.0/gtk/gtkcellrendererpixbuf.h
/usr/include/gtk-3.0/gtk/gtkcellrendererprogress.h
/usr/include/gtk-3.0/gtk/gtkcellrendererspin.h
/usr/include/gtk-3.0/gtk/gtkcellrendererspinner.h
/usr/include/gtk-3.0/gtk/gtkcellrenderertext.h
/usr/include/gtk-3.0/gtk/gtkcellrenderertoggle.h
/usr/include/gtk-3.0/gtk/gtkcellview.h
/usr/include/gtk-3.0/gtk/gtkcheckbutton.h
/usr/include/gtk-3.0/gtk/gtkcheckmenuitem.h
/usr/include/gtk-3.0/gtk/gtkclipboard.h
/usr/include/gtk-3.0/gtk/gtkcolorbutton.h
/usr/include/gtk-3.0/gtk/gtkcolorchooser.h
/usr/include/gtk-3.0/gtk/gtkcolorchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkcolorchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkcolorutils.h
/usr/include/gtk-3.0/gtk/gtkcombobox.h
/usr/include/gtk-3.0/gtk/gtkcomboboxtext.h
/usr/include/gtk-3.0/gtk/gtkcontainer.h
/usr/include/gtk-3.0/gtk/gtkcssprovider.h
/usr/include/gtk-3.0/gtk/gtkcsssection.h
/usr/include/gtk-3.0/gtk/gtkdebug.h
/usr/include/gtk-3.0/gtk/gtkdialog.h
/usr/include/gtk-3.0/gtk/gtkdnd.h
/usr/include/gtk-3.0/gtk/gtkdragdest.h
/usr/include/gtk-3.0/gtk/gtkdragsource.h
/usr/include/gtk-3.0/gtk/gtkdrawingarea.h
/usr/include/gtk-3.0/gtk/gtkeditable.h
/usr/include/gtk-3.0/gtk/gtkentry.h
/usr/include/gtk-3.0/gtk/gtkentrybuffer.h
/usr/include/gtk-3.0/gtk/gtkentrycompletion.h
/usr/include/gtk-3.0/gtk/gtkenums.h
/usr/include/gtk-3.0/gtk/gtkeventbox.h
/usr/include/gtk-3.0/gtk/gtkeventcontroller.h
/usr/include/gtk-3.0/gtk/gtkeventcontrollerkey.h
/usr/include/gtk-3.0/gtk/gtkeventcontrollermotion.h
/usr/include/gtk-3.0/gtk/gtkeventcontrollerscroll.h
/usr/include/gtk-3.0/gtk/gtkexpander.h
/usr/include/gtk-3.0/gtk/gtkfilechooser.h
/usr/include/gtk-3.0/gtk/gtkfilechooserbutton.h
/usr/include/gtk-3.0/gtk/gtkfilechooserdialog.h
/usr/include/gtk-3.0/gtk/gtkfilechoosernative.h
/usr/include/gtk-3.0/gtk/gtkfilechooserwidget.h
/usr/include/gtk-3.0/gtk/gtkfilefilter.h
/usr/include/gtk-3.0/gtk/gtkfixed.h
/usr/include/gtk-3.0/gtk/gtkflowbox.h
/usr/include/gtk-3.0/gtk/gtkfontbutton.h
/usr/include/gtk-3.0/gtk/gtkfontchooser.h
/usr/include/gtk-3.0/gtk/gtkfontchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkfontchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkframe.h
/usr/include/gtk-3.0/gtk/gtkgesture.h
/usr/include/gtk-3.0/gtk/gtkgesturedrag.h
/usr/include/gtk-3.0/gtk/gtkgesturelongpress.h
/usr/include/gtk-3.0/gtk/gtkgesturemultipress.h
/usr/include/gtk-3.0/gtk/gtkgesturepan.h
/usr/include/gtk-3.0/gtk/gtkgesturerotate.h
/usr/include/gtk-3.0/gtk/gtkgesturesingle.h
/usr/include/gtk-3.0/gtk/gtkgesturestylus.h
/usr/include/gtk-3.0/gtk/gtkgestureswipe.h
/usr/include/gtk-3.0/gtk/gtkgesturezoom.h
/usr/include/gtk-3.0/gtk/gtkglarea.h
/usr/include/gtk-3.0/gtk/gtkgrid.h
/usr/include/gtk-3.0/gtk/gtkheaderbar.h
/usr/include/gtk-3.0/gtk/gtkicontheme.h
/usr/include/gtk-3.0/gtk/gtkiconview.h
/usr/include/gtk-3.0/gtk/gtkimage.h
/usr/include/gtk-3.0/gtk/gtkimcontext.h
/usr/include/gtk-3.0/gtk/gtkimcontextinfo.h
/usr/include/gtk-3.0/gtk/gtkimcontextsimple.h
/usr/include/gtk-3.0/gtk/gtkimmodule.h
/usr/include/gtk-3.0/gtk/gtkimmulticontext.h
/usr/include/gtk-3.0/gtk/gtkinfobar.h
/usr/include/gtk-3.0/gtk/gtkinvisible.h
/usr/include/gtk-3.0/gtk/gtklabel.h
/usr/include/gtk-3.0/gtk/gtklayout.h
/usr/include/gtk-3.0/gtk/gtklevelbar.h
/usr/include/gtk-3.0/gtk/gtklinkbutton.h
/usr/include/gtk-3.0/gtk/gtklistbox.h
/usr/include/gtk-3.0/gtk/gtkliststore.h
/usr/include/gtk-3.0/gtk/gtklockbutton.h
/usr/include/gtk-3.0/gtk/gtkmain.h
/usr/include/gtk-3.0/gtk/gtkmenu.h
/usr/include/gtk-3.0/gtk/gtkmenubar.h
/usr/include/gtk-3.0/gtk/gtkmenubutton.h
/usr/include/gtk-3.0/gtk/gtkmenuitem.h
/usr/include/gtk-3.0/gtk/gtkmenushell.h
/usr/include/gtk-3.0/gtk/gtkmenutoolbutton.h
/usr/include/gtk-3.0/gtk/gtkmessagedialog.h
/usr/include/gtk-3.0/gtk/gtkmodelbutton.h
/usr/include/gtk-3.0/gtk/gtkmodules.h
/usr/include/gtk-3.0/gtk/gtkmountoperation.h
/usr/include/gtk-3.0/gtk/gtknativedialog.h
/usr/include/gtk-3.0/gtk/gtknotebook.h
/usr/include/gtk-3.0/gtk/gtkoffscreenwindow.h
/usr/include/gtk-3.0/gtk/gtkorientable.h
/usr/include/gtk-3.0/gtk/gtkoverlay.h
/usr/include/gtk-3.0/gtk/gtkpadcontroller.h
/usr/include/gtk-3.0/gtk/gtkpagesetup.h
/usr/include/gtk-3.0/gtk/gtkpaned.h
/usr/include/gtk-3.0/gtk/gtkpapersize.h
/usr/include/gtk-3.0/gtk/gtkplacessidebar.h
/usr/include/gtk-3.0/gtk/gtkplug.h
/usr/include/gtk-3.0/gtk/gtkpopover.h
/usr/include/gtk-3.0/gtk/gtkpopovermenu.h
/usr/include/gtk-3.0/gtk/gtkprintcontext.h
/usr/include/gtk-3.0/gtk/gtkprintoperation.h
/usr/include/gtk-3.0/gtk/gtkprintoperationpreview.h
/usr/include/gtk-3.0/gtk/gtkprintsettings.h
/usr/include/gtk-3.0/gtk/gtkprogressbar.h
/usr/include/gtk-3.0/gtk/gtkradiobutton.h
/usr/include/gtk-3.0/gtk/gtkradiomenuitem.h
/usr/include/gtk-3.0/gtk/gtkradiotoolbutton.h
/usr/include/gtk-3.0/gtk/gtkrange.h
/usr/include/gtk-3.0/gtk/gtkrecentchooser.h
/usr/include/gtk-3.0/gtk/gtkrecentchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkrecentchoosermenu.h
/usr/include/gtk-3.0/gtk/gtkrecentchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkrecentfilter.h
/usr/include/gtk-3.0/gtk/gtkrecentmanager.h
/usr/include/gtk-3.0/gtk/gtkrender.h
/usr/include/gtk-3.0/gtk/gtkrevealer.h
/usr/include/gtk-3.0/gtk/gtkscale.h
/usr/include/gtk-3.0/gtk/gtkscalebutton.h
/usr/include/gtk-3.0/gtk/gtkscrollable.h
/usr/include/gtk-3.0/gtk/gtkscrollbar.h
/usr/include/gtk-3.0/gtk/gtkscrolledwindow.h
/usr/include/gtk-3.0/gtk/gtksearchbar.h
/usr/include/gtk-3.0/gtk/gtksearchentry.h
/usr/include/gtk-3.0/gtk/gtkselection.h
/usr/include/gtk-3.0/gtk/gtkseparator.h
/usr/include/gtk-3.0/gtk/gtkseparatormenuitem.h
/usr/include/gtk-3.0/gtk/gtkseparatortoolitem.h
/usr/include/gtk-3.0/gtk/gtksettings.h
/usr/include/gtk-3.0/gtk/gtkshortcutlabel.h
/usr/include/gtk-3.0/gtk/gtkshortcutsgroup.h
/usr/include/gtk-3.0/gtk/gtkshortcutssection.h
/usr/include/gtk-3.0/gtk/gtkshortcutsshortcut.h
/usr/include/gtk-3.0/gtk/gtkshortcutswindow.h
/usr/include/gtk-3.0/gtk/gtkshow.h
/usr/include/gtk-3.0/gtk/gtksizegroup.h
/usr/include/gtk-3.0/gtk/gtksizerequest.h
/usr/include/gtk-3.0/gtk/gtksocket.h
/usr/include/gtk-3.0/gtk/gtkspinbutton.h
/usr/include/gtk-3.0/gtk/gtkspinner.h
/usr/include/gtk-3.0/gtk/gtkstack.h
/usr/include/gtk-3.0/gtk/gtkstacksidebar.h
/usr/include/gtk-3.0/gtk/gtkstackswitcher.h
/usr/include/gtk-3.0/gtk/gtkstatusbar.h
/usr/include/gtk-3.0/gtk/gtkstylecontext.h
/usr/include/gtk-3.0/gtk/gtkstyleprovider.h
/usr/include/gtk-3.0/gtk/gtkswitch.h
/usr/include/gtk-3.0/gtk/gtktestutils.h
/usr/include/gtk-3.0/gtk/gtktextattributes.h
/usr/include/gtk-3.0/gtk/gtktextbuffer.h
/usr/include/gtk-3.0/gtk/gtktextbufferrichtext.h
/usr/include/gtk-3.0/gtk/gtktextchild.h
/usr/include/gtk-3.0/gtk/gtktextdisplay.h
/usr/include/gtk-3.0/gtk/gtktextiter.h
/usr/include/gtk-3.0/gtk/gtktextlayout.h
/usr/include/gtk-3.0/gtk/gtktextmark.h
/usr/include/gtk-3.0/gtk/gtktexttag.h
/usr/include/gtk-3.0/gtk/gtktexttagtable.h
/usr/include/gtk-3.0/gtk/gtktextview.h
/usr/include/gtk-3.0/gtk/gtktogglebutton.h
/usr/include/gtk-3.0/gtk/gtktoggletoolbutton.h
/usr/include/gtk-3.0/gtk/gtktoolbar.h
/usr/include/gtk-3.0/gtk/gtktoolbutton.h
/usr/include/gtk-3.0/gtk/gtktoolitem.h
/usr/include/gtk-3.0/gtk/gtktoolitemgroup.h
/usr/include/gtk-3.0/gtk/gtktoolpalette.h
/usr/include/gtk-3.0/gtk/gtktoolshell.h
/usr/include/gtk-3.0/gtk/gtktooltip.h
/usr/include/gtk-3.0/gtk/gtktreednd.h
/usr/include/gtk-3.0/gtk/gtktreemodel.h
/usr/include/gtk-3.0/gtk/gtktreemodelfilter.h
/usr/include/gtk-3.0/gtk/gtktreemodelsort.h
/usr/include/gtk-3.0/gtk/gtktreeselection.h
/usr/include/gtk-3.0/gtk/gtktreesortable.h
/usr/include/gtk-3.0/gtk/gtktreestore.h
/usr/include/gtk-3.0/gtk/gtktreeview.h
/usr/include/gtk-3.0/gtk/gtktreeviewcolumn.h
/usr/include/gtk-3.0/gtk/gtktypebuiltins.h
/usr/include/gtk-3.0/gtk/gtktypes.h
/usr/include/gtk-3.0/gtk/gtkversion.h
/usr/include/gtk-3.0/gtk/gtkviewport.h
/usr/include/gtk-3.0/gtk/gtkvolumebutton.h
/usr/include/gtk-3.0/gtk/gtkwidget.h
/usr/include/gtk-3.0/gtk/gtkwidgetpath.h
/usr/include/gtk-3.0/gtk/gtkwindow.h
/usr/include/gtk-3.0/gtk/gtkwindowgroup.h
/usr/include/gtk-3.0/gtk/gtkx-autocleanups.h
/usr/include/gtk-3.0/gtk/gtkx.h
/usr/include/gtk-3.0/unix-print/gtk/gtkpagesetupunixdialog.h
/usr/include/gtk-3.0/unix-print/gtk/gtkprinter.h
/usr/include/gtk-3.0/unix-print/gtk/gtkprintjob.h
/usr/include/gtk-3.0/unix-print/gtk/gtkprintunixdialog.h
/usr/include/gtk-3.0/unix-print/gtk/gtkunixprint-autocleanups.h
/usr/include/gtk-3.0/unix-print/gtk/gtkunixprint.h
/usr/lib64/glibc-hwcaps/x86-64-v3/libgailutil-3.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libgdk-3.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libgtk-3.so
/usr/lib64/libgailutil-3.so
/usr/lib64/libgdk-3.so
/usr/lib64/libgtk-3.so
/usr/lib64/pkgconfig/gail-3.0.pc
/usr/lib64/pkgconfig/gdk-3.0.pc
/usr/lib64/pkgconfig/gdk-wayland-3.0.pc
/usr/lib64/pkgconfig/gdk-x11-3.0.pc
/usr/lib64/pkgconfig/gtk+-3.0.pc
/usr/lib64/pkgconfig/gtk+-unix-print-3.0.pc
/usr/lib64/pkgconfig/gtk+-wayland-3.0.pc
/usr/lib64/pkgconfig/gtk+-x11-3.0.pc
/usr/share/aclocal/*.m4

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-gtk3

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libgailutil-3.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgailutil-3.so.0.0.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgdk-3.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgdk-3.so.0.2404.32
/usr/lib64/glibc-hwcaps/x86-64-v3/libgtk-3.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgtk-3.so.0.2404.32
/usr/lib64/gtk-3.0/3.0.0/immodules/im-am-et.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-cedilla.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-cyrillic-translit.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-inuktitut.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ipa.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-multipress.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-thai.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ti-er.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ti-et.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-viqr.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-wayland.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-waylandgtk.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-xim.so
/usr/lib64/gtk-3.0/3.0.0/printbackends/libprintbackend-cups.so
/usr/lib64/gtk-3.0/3.0.0/printbackends/libprintbackend-file.so
/usr/lib64/gtk-3.0/3.0.0/printbackends/libprintbackend-lpr.so
/usr/lib64/libgailutil-3.so.0
/usr/lib64/libgailutil-3.so.0.0.0
/usr/lib64/libgdk-3.so.0
/usr/lib64/libgdk-3.so.0.2404.32
/usr/lib64/libgtk-3.so.0
/usr/lib64/libgtk-3.so.0.2404.32
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtk3/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/gtk3/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/icon-cache-update-trigger.service
/usr/lib/systemd/system/update-triggers.target.wants/icon-cache-update-trigger.service

%files locales -f gtk30-properties.lang -f gtk30.lang
%defattr(-,root,root,-)

