#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtk3
Version  : 3.24.36
Release  : 111
URL      : https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.36.tar.xz
Source0  : https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.36.tar.xz
Source1  : icon-cache-update-trigger.service
Summary  : GTK+ Unix print support
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: gsettings-desktop-schemas
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : cups-dev
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : fribidi-dev
BuildRequires : gobject-introspection-dev
BuildRequires : ibus
BuildRequires : ibus-dev
BuildRequires : ibus-libpinyin
BuildRequires : krb5-dev
BuildRequires : libXcursor-dev
BuildRequires : libXinerama-dev
BuildRequires : libinput-dev
BuildRequires : libxkbcommon-dev
BuildRequires : libxml2-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(atk-bridge-2.0)
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
BuildRequires : wayland-dev
BuildRequires : wayland-protocols-dev
BuildRequires : xorgproto-dev
Patch1: segfault.patch
Patch2: madvise.patch
Patch3: ignore-cache-datestamp.patch
Patch4: no-gerror.patch
Patch5: add-icon-cache-update-script.patch
Patch6: expand-search-for-icon-theme.cache.patch

%description
Summary
-------
* Do not edit the CSS directly, edit the source SCSS files
* To be able to use the latest/adequate version of SASS, install sassc
* The configure script will detect whether or not you have sassc installed;
if you do, it will regenerate the CSS every time you modify the SCSS files
and rebuild GTK+.

%prep
%setup -q -n gtk+-3.24.36
cd %{_builddir}/gtk+-3.24.36
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
pushd ..
cp -a gtk+-3.24.36 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672176468
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=512 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=512 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=512 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=512 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain --enable-wayland-backend \
--enable-x11-backend \
--enable-xdamage \
--enable-xcomposite \
--enable-xrandr \
--enable-xinerama \
--disable-papi \
--enable-explicit-deps=yes \
--with-included-immodules=wayland,xim \
--enable-colord=no \
--enable-installed-tests  builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain --enable-wayland-backend \
--enable-x11-backend \
--enable-xdamage \
--enable-xcomposite \
--enable-xrandr \
--enable-xinerama \
--disable-papi \
--enable-explicit-deps=yes \
--with-included-immodules=wayland,xim \
--enable-colord=no \
--enable-installed-tests  builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gtk3
cp %{_builddir}/gtk+-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gtk3/ba8966e2473a9969bdcab3dc82274c817cfd98a1
cp %{_builddir}/gtk+-%{version}/gdk/COPYING %{buildroot}/usr/share/package-licenses/gtk3/01a6b4bf79aca9b556822601186afab86e8c4fbf
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/icon-cache-update-trigger.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants
ln -s /usr/lib/systemd/system/icon-cache-update-trigger.service %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/icon-cache-update-trigger.service
install -m 0755 icon-cache-update.sh %{buildroot}/usr/bin

mkdir -p %{buildroot}/usr/lib64/gtk-3.0/3.0.0/
%{buildroot}/usr/bin/gtk-query-immodules-3.0 > %{buildroot}/usr/lib64/gtk-3.0/3.0.0/immodules.cache
sed -i -e "s/.*Created by.*//g"  %{buildroot}/usr/lib64/gtk-3.0/3.0.0/immodules.cache
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
