#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : gtk3
Version  : 3.24.37
Release  : 116
URL      : https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.37.tar.xz
Source0  : https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.37.tar.xz
Source1  : icon-cache-update-trigger.service
Summary  : GTK+ Unix print support
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: gtk3-bin = %{version}-%{release}
Requires: gtk3-data = %{version}-%{release}
Requires: gtk3-filemap = %{version}-%{release}
Requires: gtk3-lib = %{version}-%{release}
Requires: gtk3-license = %{version}-%{release}
Requires: gtk3-locales = %{version}-%{release}
Requires: gtk3-services = %{version}-%{release}
Requires: gsettings-desktop-schemas
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : colord-dev
BuildRequires : cups-dev
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : fribidi-dev
BuildRequires : gobject-introspection-dev
BuildRequires : ibus
BuildRequires : ibus-dev
BuildRequires : ibus-libpinyin
BuildRequires : krb5-dev
BuildRequires : libXcursor-dev
BuildRequires : libXinerama-dev
BuildRequires : libinput-dev
BuildRequires : libxkbcommon-dev
BuildRequires : libxml2-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(atk-bridge-2.0)
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
BuildRequires : sassc
BuildRequires : wayland-dev
BuildRequires : wayland-protocols-dev
BuildRequires : xorgproto-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: segfault.patch
Patch2: madvise.patch
Patch3: ignore-cache-datestamp.patch
Patch4: no-gerror.patch
Patch5: add-icon-cache-update-script.patch
Patch6: expand-search-for-icon-theme.cache.patch

%description
Summary
-------
* Do not edit the CSS directly, edit the source SCSS files
* To be able to use the latest/adequate version of SASS, install sassc
* The configure script will detect whether or not you have sassc installed;
if you do, it will regenerate the CSS every time you modify the SCSS files
and rebuild GTK+.

%package bin
Summary: bin components for the gtk3 package.
Group: Binaries
Requires: gtk3-data = %{version}-%{release}
Requires: gtk3-license = %{version}-%{release}
Requires: gtk3-services = %{version}-%{release}
Requires: gtk3-filemap = %{version}-%{release}

%description bin
bin components for the gtk3 package.


%package data
Summary: data components for the gtk3 package.
Group: Data

%description data
data components for the gtk3 package.


%package dev
Summary: dev components for the gtk3 package.
Group: Development
Requires: gtk3-lib = %{version}-%{release}
Requires: gtk3-bin = %{version}-%{release}
Requires: gtk3-data = %{version}-%{release}
Provides: gtk3-devel = %{version}-%{release}
Requires: gtk3 = %{version}-%{release}

%description dev
dev components for the gtk3 package.


%package filemap
Summary: filemap components for the gtk3 package.
Group: Default

%description filemap
filemap components for the gtk3 package.


%package lib
Summary: lib components for the gtk3 package.
Group: Libraries
Requires: gtk3-data = %{version}-%{release}
Requires: gtk3-license = %{version}-%{release}
Requires: gtk3-filemap = %{version}-%{release}

%description lib
lib components for the gtk3 package.


%package license
Summary: license components for the gtk3 package.
Group: Default

%description license
license components for the gtk3 package.


%package locales
Summary: locales components for the gtk3 package.
Group: Default

%description locales
locales components for the gtk3 package.


%package services
Summary: services components for the gtk3 package.
Group: Systemd services

%description services
services components for the gtk3 package.


%package tests
Summary: tests components for the gtk3 package.
Group: Default
Requires: gtk3 = %{version}-%{release}

%description tests
tests components for the gtk3 package.


%prep
%setup -q -n gtk+-3.24.37
cd %{_builddir}/gtk+-3.24.37
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
pushd ..
cp -a gtk+-3.24.37 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680034124
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dinstalled_tests=true  builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dinstalled_tests=true  builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gtk3
cp %{_builddir}/gtk+-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gtk3/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/gtk+-%{version}/gdk/COPYING %{buildroot}/usr/share/package-licenses/gtk3/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gtk30-properties
%find_lang gtk30
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/icon-cache-update-trigger.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants
ln -s /usr/lib/systemd/system/icon-cache-update-trigger.service %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/icon-cache-update-trigger.service
install -m 0755 icon-cache-update.sh %{buildroot}/usr/bin

mkdir -p %{buildroot}/usr/lib64/gtk-3.0/3.0.0/
%{buildroot}/usr/bin/gtk-query-immodules-3.0 > %{buildroot}/usr/lib64/gtk-3.0/3.0.0/immodules.cache
sed -i -e "s/.*Created by.*//g"  %{buildroot}/usr/lib64/gtk-3.0/3.0.0/immodules.cache
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/gtk-3.0/3.0.0/immodules.cache

%files bin
%defattr(-,root,root,-)
/usr/bin/gtk-builder-tool
/usr/bin/gtk-encode-symbolic-svg
/usr/bin/gtk-launch
/usr/bin/gtk-query-immodules-3.0
/usr/bin/gtk-query-settings
/usr/bin/gtk-update-icon-cache
/usr/bin/gtk3-demo
/usr/bin/gtk3-demo-application
/usr/bin/gtk3-icon-browser
/usr/bin/gtk3-widget-factory
/usr/bin/icon-cache-update.sh
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gdk-3.0.typelib
/usr/lib64/girepository-1.0/GdkX11-3.0.typelib
/usr/lib64/girepository-1.0/Gtk-3.0.typelib
/usr/share/applications/gtk3-demo.desktop
/usr/share/applications/gtk3-icon-browser.desktop
/usr/share/applications/gtk3-widget-factory.desktop
/usr/share/gettext/its/gtkbuilder.its
/usr/share/gettext/its/gtkbuilder.loc
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gtk.Demo.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.ColorChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.EmojiChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
/usr/share/glib-2.0/schemas/org.gtk.exampleapp.gschema.xml
/usr/share/gtk-3.0/emoji/de.gresource
/usr/share/gtk-3.0/emoji/es.gresource
/usr/share/gtk-3.0/emoji/fr.gresource
/usr/share/gtk-3.0/emoji/zh.gresource
/usr/share/gtk-3.0/gtkbuilder.rng
/usr/share/gtk-3.0/valgrind/gtk.supp
/usr/share/icons/hicolor/16x16/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/16x16/apps/gtk3-demo.png
/usr/share/icons/hicolor/16x16/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/16x16/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/22x22/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/22x22/apps/gtk3-demo.png
/usr/share/icons/hicolor/22x22/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/22x22/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/24x24/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/24x24/apps/gtk3-demo.png
/usr/share/icons/hicolor/24x24/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/24x24/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/256x256/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/256x256/apps/gtk3-demo.png
/usr/share/icons/hicolor/256x256/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/256x256/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/32x32/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/32x32/apps/gtk3-demo.png
/usr/share/icons/hicolor/32x32/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/32x32/apps/gtk3-widget-factory.png
/usr/share/icons/hicolor/48x48/apps/gtk3-demo-symbolic.symbolic.png
/usr/share/icons/hicolor/48x48/apps/gtk3-demo.png
/usr/share/icons/hicolor/48x48/apps/gtk3-widget-factory-symbolic.symbolic.png
/usr/share/icons/hicolor/48x48/apps/gtk3-widget-factory.png
/usr/share/themes/Default/gtk-3.0/gtk-keys.css
/usr/share/themes/Emacs/gtk-3.0/gtk-keys.css

%files dev
%defattr(-,root,root,-)
/usr/include/gail-3.0/libgail-util/gail-util.h
/usr/include/gail-3.0/libgail-util/gailmisc.h
/usr/include/gail-3.0/libgail-util/gailtextutil.h
/usr/include/gtk-3.0/gdk/deprecated/gdkcolor.h
/usr/include/gtk-3.0/gdk/gdk-autocleanup.h
/usr/include/gtk-3.0/gdk/gdk.h
/usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h
/usr/include/gtk-3.0/gdk/gdkcairo.h
/usr/include/gtk-3.0/gdk/gdkconfig.h
/usr/include/gtk-3.0/gdk/gdkcursor.h
/usr/include/gtk-3.0/gdk/gdkdevice.h
/usr/include/gtk-3.0/gdk/gdkdevicemanager.h
/usr/include/gtk-3.0/gdk/gdkdevicepad.h
/usr/include/gtk-3.0/gdk/gdkdevicetool.h
/usr/include/gtk-3.0/gdk/gdkdisplay.h
/usr/include/gtk-3.0/gdk/gdkdisplaymanager.h
/usr/include/gtk-3.0/gdk/gdkdnd.h
/usr/include/gtk-3.0/gdk/gdkdrawingcontext.h
/usr/include/gtk-3.0/gdk/gdkenumtypes.h
/usr/include/gtk-3.0/gdk/gdkevents.h
/usr/include/gtk-3.0/gdk/gdkframeclock.h
/usr/include/gtk-3.0/gdk/gdkframetimings.h
/usr/include/gtk-3.0/gdk/gdkglcontext.h
/usr/include/gtk-3.0/gdk/gdkkeys.h
/usr/include/gtk-3.0/gdk/gdkkeysyms-compat.h
/usr/include/gtk-3.0/gdk/gdkkeysyms.h
/usr/include/gtk-3.0/gdk/gdkmain.h
/usr/include/gtk-3.0/gdk/gdkmonitor.h
/usr/include/gtk-3.0/gdk/gdkpango.h
/usr/include/gtk-3.0/gdk/gdkpixbuf.h
/usr/include/gtk-3.0/gdk/gdkprivate.h
/usr/include/gtk-3.0/gdk/gdkproperty.h
/usr/include/gtk-3.0/gdk/gdkrectangle.h
/usr/include/gtk-3.0/gdk/gdkrgba.h
/usr/include/gtk-3.0/gdk/gdkscreen.h
/usr/include/gtk-3.0/gdk/gdkseat.h
/usr/include/gtk-3.0/gdk/gdkselection.h
/usr/include/gtk-3.0/gdk/gdktestutils.h
/usr/include/gtk-3.0/gdk/gdkthreads.h
/usr/include/gtk-3.0/gdk/gdktypes.h
/usr/include/gtk-3.0/gdk/gdkversionmacros.h
/usr/include/gtk-3.0/gdk/gdkvisual.h
/usr/include/gtk-3.0/gdk/gdkwayland.h
/usr/include/gtk-3.0/gdk/gdkwindow.h
/usr/include/gtk-3.0/gdk/gdkx.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylanddevice.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylanddisplay.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandglcontext.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandmonitor.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandselection.h
/usr/include/gtk-3.0/gdk/wayland/gdkwaylandwindow.h
/usr/include/gtk-3.0/gdk/x11/gdkx-autocleanups.h
/usr/include/gtk-3.0/gdk/x11/gdkx11applaunchcontext.h
/usr/include/gtk-3.0/gdk/x11/gdkx11cursor.h
/usr/include/gtk-3.0/gdk/x11/gdkx11device-core.h
/usr/include/gtk-3.0/gdk/x11/gdkx11device-xi2.h
/usr/include/gtk-3.0/gdk/x11/gdkx11device.h
/usr/include/gtk-3.0/gdk/x11/gdkx11devicemanager-core.h
/usr/include/gtk-3.0/gdk/x11/gdkx11devicemanager-xi2.h
/usr/include/gtk-3.0/gdk/x11/gdkx11devicemanager.h
/usr/include/gtk-3.0/gdk/x11/gdkx11display.h
/usr/include/gtk-3.0/gdk/x11/gdkx11displaymanager.h
/usr/include/gtk-3.0/gdk/x11/gdkx11dnd.h
/usr/include/gtk-3.0/gdk/x11/gdkx11glcontext.h
/usr/include/gtk-3.0/gdk/x11/gdkx11keys.h
/usr/include/gtk-3.0/gdk/x11/gdkx11monitor.h
/usr/include/gtk-3.0/gdk/x11/gdkx11property.h
/usr/include/gtk-3.0/gdk/x11/gdkx11screen.h
/usr/include/gtk-3.0/gdk/x11/gdkx11selection.h
/usr/include/gtk-3.0/gdk/x11/gdkx11utils.h
/usr/include/gtk-3.0/gdk/x11/gdkx11visual.h
/usr/include/gtk-3.0/gdk/x11/gdkx11window.h
/usr/include/gtk-3.0/gtk/a11y/gtk-a11y-autocleanups.h
/usr/include/gtk-3.0/gtk/a11y/gtkarrowaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkbooleancellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcellaccessibleparent.h
/usr/include/gtk-3.0/gtk/a11y/gtkcheckmenuitemaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcomboboxaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcontaineraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkcontainercellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkentryaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkexpanderaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkfilechooserwidgetaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkflowboxaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkflowboxchildaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkframeaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkheaderbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkiconviewaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkimageaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkimagecellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklabelaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklevelbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklinkbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklistboxaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklistboxrowaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtklockbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenuaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenubuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenuitemaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkmenushellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtknotebookaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtknotebookpageaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkpanedaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkplugaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkpopoveraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkprogressbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkradiobuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkradiomenuitemaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkrangeaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkrenderercellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkscaleaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkscalebuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkscrolledwindowaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtksocketaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkspinbuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkspinneraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkstackaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkstatusbaraccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkswitchaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktextcellaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktextviewaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktogglebuttonaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktoplevelaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtktreeviewaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkwidgetaccessible.h
/usr/include/gtk-3.0/gtk/a11y/gtkwindowaccessible.h
/usr/include/gtk-3.0/gtk/deprecated/gtkaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkactiongroup.h
/usr/include/gtk-3.0/gtk/deprecated/gtkactivatable.h
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h
/usr/include/gtk-3.0/gtk/deprecated/gtkarrow.h
/usr/include/gtk-3.0/gtk/deprecated/gtkcolorsel.h
/usr/include/gtk-3.0/gtk/deprecated/gtkcolorseldialog.h
/usr/include/gtk-3.0/gtk/deprecated/gtkfontsel.h
/usr/include/gtk-3.0/gtk/deprecated/gtkgradient.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhandlebox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhbbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhpaned.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhscale.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhscrollbar.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhseparator.h
/usr/include/gtk-3.0/gtk/deprecated/gtkhsv.h
/usr/include/gtk-3.0/gtk/deprecated/gtkiconfactory.h
/usr/include/gtk-3.0/gtk/deprecated/gtkimagemenuitem.h
/usr/include/gtk-3.0/gtk/deprecated/gtkmisc.h
/usr/include/gtk-3.0/gtk/deprecated/gtknumerableicon.h
/usr/include/gtk-3.0/gtk/deprecated/gtkradioaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkrc.h
/usr/include/gtk-3.0/gtk/deprecated/gtkrecentaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstatusicon.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstock.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstyle.h
/usr/include/gtk-3.0/gtk/deprecated/gtkstyleproperties.h
/usr/include/gtk-3.0/gtk/deprecated/gtksymboliccolor.h
/usr/include/gtk-3.0/gtk/deprecated/gtktable.h
/usr/include/gtk-3.0/gtk/deprecated/gtktearoffmenuitem.h
/usr/include/gtk-3.0/gtk/deprecated/gtkthemingengine.h
/usr/include/gtk-3.0/gtk/deprecated/gtktoggleaction.h
/usr/include/gtk-3.0/gtk/deprecated/gtkuimanager.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvbbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvbox.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvpaned.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvscale.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvscrollbar.h
/usr/include/gtk-3.0/gtk/deprecated/gtkvseparator.h
/usr/include/gtk-3.0/gtk/gtk-a11y.h
/usr/include/gtk-3.0/gtk/gtk-autocleanups.h
/usr/include/gtk-3.0/gtk/gtk.h
/usr/include/gtk-3.0/gtk/gtkaboutdialog.h
/usr/include/gtk-3.0/gtk/gtkaccelgroup.h
/usr/include/gtk-3.0/gtk/gtkaccellabel.h
/usr/include/gtk-3.0/gtk/gtkaccelmap.h
/usr/include/gtk-3.0/gtk/gtkaccessible.h
/usr/include/gtk-3.0/gtk/gtkactionable.h
/usr/include/gtk-3.0/gtk/gtkactionbar.h
/usr/include/gtk-3.0/gtk/gtkadjustment.h
/usr/include/gtk-3.0/gtk/gtkappchooser.h
/usr/include/gtk-3.0/gtk/gtkappchooserbutton.h
/usr/include/gtk-3.0/gtk/gtkappchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkappchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkapplication.h
/usr/include/gtk-3.0/gtk/gtkapplicationwindow.h
/usr/include/gtk-3.0/gtk/gtkaspectframe.h
/usr/include/gtk-3.0/gtk/gtkassistant.h
/usr/include/gtk-3.0/gtk/gtkbbox.h
/usr/include/gtk-3.0/gtk/gtkbin.h
/usr/include/gtk-3.0/gtk/gtkbindings.h
/usr/include/gtk-3.0/gtk/gtkborder.h
/usr/include/gtk-3.0/gtk/gtkbox.h
/usr/include/gtk-3.0/gtk/gtkbuildable.h
/usr/include/gtk-3.0/gtk/gtkbuilder.h
/usr/include/gtk-3.0/gtk/gtkbutton.h
/usr/include/gtk-3.0/gtk/gtkcalendar.h
/usr/include/gtk-3.0/gtk/gtkcellarea.h
/usr/include/gtk-3.0/gtk/gtkcellareabox.h
/usr/include/gtk-3.0/gtk/gtkcellareacontext.h
/usr/include/gtk-3.0/gtk/gtkcelleditable.h
/usr/include/gtk-3.0/gtk/gtkcelllayout.h
/usr/include/gtk-3.0/gtk/gtkcellrenderer.h
/usr/include/gtk-3.0/gtk/gtkcellrendereraccel.h
/usr/include/gtk-3.0/gtk/gtkcellrenderercombo.h
/usr/include/gtk-3.0/gtk/gtkcellrendererpixbuf.h
/usr/include/gtk-3.0/gtk/gtkcellrendererprogress.h
/usr/include/gtk-3.0/gtk/gtkcellrendererspin.h
/usr/include/gtk-3.0/gtk/gtkcellrendererspinner.h
/usr/include/gtk-3.0/gtk/gtkcellrenderertext.h
/usr/include/gtk-3.0/gtk/gtkcellrenderertoggle.h
/usr/include/gtk-3.0/gtk/gtkcellview.h
/usr/include/gtk-3.0/gtk/gtkcheckbutton.h
/usr/include/gtk-3.0/gtk/gtkcheckmenuitem.h
/usr/include/gtk-3.0/gtk/gtkclipboard.h
/usr/include/gtk-3.0/gtk/gtkcolorbutton.h
/usr/include/gtk-3.0/gtk/gtkcolorchooser.h
/usr/include/gtk-3.0/gtk/gtkcolorchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkcolorchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkcolorutils.h
/usr/include/gtk-3.0/gtk/gtkcombobox.h
/usr/include/gtk-3.0/gtk/gtkcomboboxtext.h
/usr/include/gtk-3.0/gtk/gtkcontainer.h
/usr/include/gtk-3.0/gtk/gtkcssprovider.h
/usr/include/gtk-3.0/gtk/gtkcsssection.h
/usr/include/gtk-3.0/gtk/gtkdebug.h
/usr/include/gtk-3.0/gtk/gtkdialog.h
/usr/include/gtk-3.0/gtk/gtkdnd.h
/usr/include/gtk-3.0/gtk/gtkdragdest.h
/usr/include/gtk-3.0/gtk/gtkdragsource.h
/usr/include/gtk-3.0/gtk/gtkdrawingarea.h
/usr/include/gtk-3.0/gtk/gtkeditable.h
/usr/include/gtk-3.0/gtk/gtkentry.h
/usr/include/gtk-3.0/gtk/gtkentrybuffer.h
/usr/include/gtk-3.0/gtk/gtkentrycompletion.h
/usr/include/gtk-3.0/gtk/gtkenums.h
/usr/include/gtk-3.0/gtk/gtkeventbox.h
/usr/include/gtk-3.0/gtk/gtkeventcontroller.h
/usr/include/gtk-3.0/gtk/gtkeventcontrollerkey.h
/usr/include/gtk-3.0/gtk/gtkeventcontrollermotion.h
/usr/include/gtk-3.0/gtk/gtkeventcontrollerscroll.h
/usr/include/gtk-3.0/gtk/gtkexpander.h
/usr/include/gtk-3.0/gtk/gtkfilechooser.h
/usr/include/gtk-3.0/gtk/gtkfilechooserbutton.h
/usr/include/gtk-3.0/gtk/gtkfilechooserdialog.h
/usr/include/gtk-3.0/gtk/gtkfilechoosernative.h
/usr/include/gtk-3.0/gtk/gtkfilechooserwidget.h
/usr/include/gtk-3.0/gtk/gtkfilefilter.h
/usr/include/gtk-3.0/gtk/gtkfixed.h
/usr/include/gtk-3.0/gtk/gtkflowbox.h
/usr/include/gtk-3.0/gtk/gtkfontbutton.h
/usr/include/gtk-3.0/gtk/gtkfontchooser.h
/usr/include/gtk-3.0/gtk/gtkfontchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkfontchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkframe.h
/usr/include/gtk-3.0/gtk/gtkgesture.h
/usr/include/gtk-3.0/gtk/gtkgesturedrag.h
/usr/include/gtk-3.0/gtk/gtkgesturelongpress.h
/usr/include/gtk-3.0/gtk/gtkgesturemultipress.h
/usr/include/gtk-3.0/gtk/gtkgesturepan.h
/usr/include/gtk-3.0/gtk/gtkgesturerotate.h
/usr/include/gtk-3.0/gtk/gtkgesturesingle.h
/usr/include/gtk-3.0/gtk/gtkgesturestylus.h
/usr/include/gtk-3.0/gtk/gtkgestureswipe.h
/usr/include/gtk-3.0/gtk/gtkgesturezoom.h
/usr/include/gtk-3.0/gtk/gtkglarea.h
/usr/include/gtk-3.0/gtk/gtkgrid.h
/usr/include/gtk-3.0/gtk/gtkheaderbar.h
/usr/include/gtk-3.0/gtk/gtkicontheme.h
/usr/include/gtk-3.0/gtk/gtkiconview.h
/usr/include/gtk-3.0/gtk/gtkimage.h
/usr/include/gtk-3.0/gtk/gtkimcontext.h
/usr/include/gtk-3.0/gtk/gtkimcontextinfo.h
/usr/include/gtk-3.0/gtk/gtkimcontextsimple.h
/usr/include/gtk-3.0/gtk/gtkimmodule.h
/usr/include/gtk-3.0/gtk/gtkimmulticontext.h
/usr/include/gtk-3.0/gtk/gtkinfobar.h
/usr/include/gtk-3.0/gtk/gtkinvisible.h
/usr/include/gtk-3.0/gtk/gtklabel.h
/usr/include/gtk-3.0/gtk/gtklayout.h
/usr/include/gtk-3.0/gtk/gtklevelbar.h
/usr/include/gtk-3.0/gtk/gtklinkbutton.h
/usr/include/gtk-3.0/gtk/gtklistbox.h
/usr/include/gtk-3.0/gtk/gtkliststore.h
/usr/include/gtk-3.0/gtk/gtklockbutton.h
/usr/include/gtk-3.0/gtk/gtkmain.h
/usr/include/gtk-3.0/gtk/gtkmenu.h
/usr/include/gtk-3.0/gtk/gtkmenubar.h
/usr/include/gtk-3.0/gtk/gtkmenubutton.h
/usr/include/gtk-3.0/gtk/gtkmenuitem.h
/usr/include/gtk-3.0/gtk/gtkmenushell.h
/usr/include/gtk-3.0/gtk/gtkmenutoolbutton.h
/usr/include/gtk-3.0/gtk/gtkmessagedialog.h
/usr/include/gtk-3.0/gtk/gtkmodelbutton.h
/usr/include/gtk-3.0/gtk/gtkmodules.h
/usr/include/gtk-3.0/gtk/gtkmountoperation.h
/usr/include/gtk-3.0/gtk/gtknativedialog.h
/usr/include/gtk-3.0/gtk/gtknotebook.h
/usr/include/gtk-3.0/gtk/gtkoffscreenwindow.h
/usr/include/gtk-3.0/gtk/gtkorientable.h
/usr/include/gtk-3.0/gtk/gtkoverlay.h
/usr/include/gtk-3.0/gtk/gtkpadcontroller.h
/usr/include/gtk-3.0/gtk/gtkpagesetup.h
/usr/include/gtk-3.0/gtk/gtkpaned.h
/usr/include/gtk-3.0/gtk/gtkpapersize.h
/usr/include/gtk-3.0/gtk/gtkplacessidebar.h
/usr/include/gtk-3.0/gtk/gtkplug.h
/usr/include/gtk-3.0/gtk/gtkpopover.h
/usr/include/gtk-3.0/gtk/gtkpopovermenu.h
/usr/include/gtk-3.0/gtk/gtkprintcontext.h
/usr/include/gtk-3.0/gtk/gtkprintoperation.h
/usr/include/gtk-3.0/gtk/gtkprintoperationpreview.h
/usr/include/gtk-3.0/gtk/gtkprintsettings.h
/usr/include/gtk-3.0/gtk/gtkprogressbar.h
/usr/include/gtk-3.0/gtk/gtkradiobutton.h
/usr/include/gtk-3.0/gtk/gtkradiomenuitem.h
/usr/include/gtk-3.0/gtk/gtkradiotoolbutton.h
/usr/include/gtk-3.0/gtk/gtkrange.h
/usr/include/gtk-3.0/gtk/gtkrecentchooser.h
/usr/include/gtk-3.0/gtk/gtkrecentchooserdialog.h
/usr/include/gtk-3.0/gtk/gtkrecentchoosermenu.h
/usr/include/gtk-3.0/gtk/gtkrecentchooserwidget.h
/usr/include/gtk-3.0/gtk/gtkrecentfilter.h
/usr/include/gtk-3.0/gtk/gtkrecentmanager.h
/usr/include/gtk-3.0/gtk/gtkrender.h
/usr/include/gtk-3.0/gtk/gtkrevealer.h
/usr/include/gtk-3.0/gtk/gtkscale.h
/usr/include/gtk-3.0/gtk/gtkscalebutton.h
/usr/include/gtk-3.0/gtk/gtkscrollable.h
/usr/include/gtk-3.0/gtk/gtkscrollbar.h
/usr/include/gtk-3.0/gtk/gtkscrolledwindow.h
/usr/include/gtk-3.0/gtk/gtksearchbar.h
/usr/include/gtk-3.0/gtk/gtksearchentry.h
/usr/include/gtk-3.0/gtk/gtkselection.h
/usr/include/gtk-3.0/gtk/gtkseparator.h
/usr/include/gtk-3.0/gtk/gtkseparatormenuitem.h
/usr/include/gtk-3.0/gtk/gtkseparatortoolitem.h
/usr/include/gtk-3.0/gtk/gtksettings.h
/usr/include/gtk-3.0/gtk/gtkshortcutlabel.h
/usr/include/gtk-3.0/gtk/gtkshortcutsgroup.h
/usr/include/gtk-3.0/gtk/gtkshortcutssection.h
/usr/include/gtk-3.0/gtk/gtkshortcutsshortcut.h
/usr/include/gtk-3.0/gtk/gtkshortcutswindow.h
/usr/include/gtk-3.0/gtk/gtkshow.h
/usr/include/gtk-3.0/gtk/gtksizegroup.h
/usr/include/gtk-3.0/gtk/gtksizerequest.h
/usr/include/gtk-3.0/gtk/gtksocket.h
/usr/include/gtk-3.0/gtk/gtkspinbutton.h
/usr/include/gtk-3.0/gtk/gtkspinner.h
/usr/include/gtk-3.0/gtk/gtkstack.h
/usr/include/gtk-3.0/gtk/gtkstacksidebar.h
/usr/include/gtk-3.0/gtk/gtkstackswitcher.h
/usr/include/gtk-3.0/gtk/gtkstatusbar.h
/usr/include/gtk-3.0/gtk/gtkstylecontext.h
/usr/include/gtk-3.0/gtk/gtkstyleprovider.h
/usr/include/gtk-3.0/gtk/gtkswitch.h
/usr/include/gtk-3.0/gtk/gtktestutils.h
/usr/include/gtk-3.0/gtk/gtktextattributes.h
/usr/include/gtk-3.0/gtk/gtktextbuffer.h
/usr/include/gtk-3.0/gtk/gtktextbufferrichtext.h
/usr/include/gtk-3.0/gtk/gtktextchild.h
/usr/include/gtk-3.0/gtk/gtktextdisplay.h
/usr/include/gtk-3.0/gtk/gtktextiter.h
/usr/include/gtk-3.0/gtk/gtktextlayout.h
/usr/include/gtk-3.0/gtk/gtktextmark.h
/usr/include/gtk-3.0/gtk/gtktexttag.h
/usr/include/gtk-3.0/gtk/gtktexttagtable.h
/usr/include/gtk-3.0/gtk/gtktextview.h
/usr/include/gtk-3.0/gtk/gtktogglebutton.h
/usr/include/gtk-3.0/gtk/gtktoggletoolbutton.h
/usr/include/gtk-3.0/gtk/gtktoolbar.h
/usr/include/gtk-3.0/gtk/gtktoolbutton.h
/usr/include/gtk-3.0/gtk/gtktoolitem.h
/usr/include/gtk-3.0/gtk/gtktoolitemgroup.h
/usr/include/gtk-3.0/gtk/gtktoolpalette.h
/usr/include/gtk-3.0/gtk/gtktoolshell.h
/usr/include/gtk-3.0/gtk/gtktooltip.h
/usr/include/gtk-3.0/gtk/gtktreednd.h
/usr/include/gtk-3.0/gtk/gtktreemodel.h
/usr/include/gtk-3.0/gtk/gtktreemodelfilter.h
/usr/include/gtk-3.0/gtk/gtktreemodelsort.h
/usr/include/gtk-3.0/gtk/gtktreeselection.h
/usr/include/gtk-3.0/gtk/gtktreesortable.h
/usr/include/gtk-3.0/gtk/gtktreestore.h
/usr/include/gtk-3.0/gtk/gtktreeview.h
/usr/include/gtk-3.0/gtk/gtktreeviewcolumn.h
/usr/include/gtk-3.0/gtk/gtktypebuiltins.h
/usr/include/gtk-3.0/gtk/gtktypes.h
/usr/include/gtk-3.0/gtk/gtkversion.h
/usr/include/gtk-3.0/gtk/gtkviewport.h
/usr/include/gtk-3.0/gtk/gtkvolumebutton.h
/usr/include/gtk-3.0/gtk/gtkwidget.h
/usr/include/gtk-3.0/gtk/gtkwidgetpath.h
/usr/include/gtk-3.0/gtk/gtkwindow.h
/usr/include/gtk-3.0/gtk/gtkwindowgroup.h
/usr/include/gtk-3.0/gtk/gtkx-autocleanups.h
/usr/include/gtk-3.0/gtk/gtkx.h
/usr/include/gtk-3.0/unix-print/gtk/gtkpagesetupunixdialog.h
/usr/include/gtk-3.0/unix-print/gtk/gtkprinter.h
/usr/include/gtk-3.0/unix-print/gtk/gtkprintjob.h
/usr/include/gtk-3.0/unix-print/gtk/gtkprintunixdialog.h
/usr/include/gtk-3.0/unix-print/gtk/gtkunixprint-autocleanups.h
/usr/include/gtk-3.0/unix-print/gtk/gtkunixprint.h
/usr/lib64/glibc-hwcaps/x86-64-v3/libgailutil-3.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libgdk-3.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libgtk-3.so
/usr/lib64/libgailutil-3.so
/usr/lib64/libgdk-3.so
/usr/lib64/libgtk-3.so
/usr/lib64/pkgconfig/gail-3.0.pc
/usr/lib64/pkgconfig/gdk-3.0.pc
/usr/lib64/pkgconfig/gdk-wayland-3.0.pc
/usr/lib64/pkgconfig/gdk-x11-3.0.pc
/usr/lib64/pkgconfig/gtk+-3.0.pc
/usr/lib64/pkgconfig/gtk+-unix-print-3.0.pc
/usr/lib64/pkgconfig/gtk+-wayland-3.0.pc
/usr/lib64/pkgconfig/gtk+-x11-3.0.pc
/usr/share/aclocal/*.m4

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-gtk3

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libgailutil-3.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgailutil-3.so.0.0.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgdk-3.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgdk-3.so.0.2405.32
/usr/lib64/glibc-hwcaps/x86-64-v3/libgtk-3.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libgtk-3.so.0.2405.32
/usr/lib64/gtk-3.0/3.0.0/immodules/im-am-et.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-cedilla.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-cyrillic-translit.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-inuktitut.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ipa.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-multipress.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-thai.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ti-er.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ti-et.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-viqr.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-wayland.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-xim.so
/usr/lib64/gtk-3.0/3.0.0/printbackends/libprintbackend-cups.so
/usr/lib64/gtk-3.0/3.0.0/printbackends/libprintbackend-file.so
/usr/lib64/gtk-3.0/3.0.0/printbackends/libprintbackend-lpr.so
/usr/lib64/libgailutil-3.so.0
/usr/lib64/libgailutil-3.so.0.0.0
/usr/lib64/libgdk-3.so.0
/usr/lib64/libgdk-3.so.0.2405.32
/usr/lib64/libgtk-3.so.0
/usr/lib64/libgtk-3.so.0.2405.32
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtk3/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/gtk3/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/icon-cache-update-trigger.service
/usr/lib/systemd/system/update-triggers.target.wants/icon-cache-update-trigger.service

%files tests
%defattr(-,root,root,-)
/usr/libexec/installed-tests/gtk+/a11ytests/about.txt
/usr/libexec/installed-tests/gtk+/a11ytests/about.ui
/usr/libexec/installed-tests/gtk+/a11ytests/accessible-name.txt
/usr/libexec/installed-tests/gtk+/a11ytests/accessible-name.ui
/usr/libexec/installed-tests/gtk+/a11ytests/actionbar.txt
/usr/libexec/installed-tests/gtk+/a11ytests/actionbar.ui
/usr/libexec/installed-tests/gtk+/a11ytests/assistant.txt
/usr/libexec/installed-tests/gtk+/a11ytests/assistant.ui
/usr/libexec/installed-tests/gtk+/a11ytests/buttons.txt
/usr/libexec/installed-tests/gtk+/a11ytests/buttons.ui
/usr/libexec/installed-tests/gtk+/a11ytests/calendar.txt
/usr/libexec/installed-tests/gtk+/a11ytests/calendar.ui
/usr/libexec/installed-tests/gtk+/a11ytests/colorchooser.txt
/usr/libexec/installed-tests/gtk+/a11ytests/colorchooser.ui
/usr/libexec/installed-tests/gtk+/a11ytests/combos.txt
/usr/libexec/installed-tests/gtk+/a11ytests/combos.ui
/usr/libexec/installed-tests/gtk+/a11ytests/entries.txt
/usr/libexec/installed-tests/gtk+/a11ytests/entries.ui
/usr/libexec/installed-tests/gtk+/a11ytests/expander.txt
/usr/libexec/installed-tests/gtk+/a11ytests/expander.ui
/usr/libexec/installed-tests/gtk+/a11ytests/headerbar.txt
/usr/libexec/installed-tests/gtk+/a11ytests/headerbar.ui
/usr/libexec/installed-tests/gtk+/a11ytests/hello-world.txt
/usr/libexec/installed-tests/gtk+/a11ytests/hello-world.ui
/usr/libexec/installed-tests/gtk+/a11ytests/iconview.txt
/usr/libexec/installed-tests/gtk+/a11ytests/iconview.ui
/usr/libexec/installed-tests/gtk+/a11ytests/infobar.txt
/usr/libexec/installed-tests/gtk+/a11ytests/infobar.ui
/usr/libexec/installed-tests/gtk+/a11ytests/label.txt
/usr/libexec/installed-tests/gtk+/a11ytests/label.ui
/usr/libexec/installed-tests/gtk+/a11ytests/link.txt
/usr/libexec/installed-tests/gtk+/a11ytests/link.ui
/usr/libexec/installed-tests/gtk+/a11ytests/listbox.txt
/usr/libexec/installed-tests/gtk+/a11ytests/listbox.ui
/usr/libexec/installed-tests/gtk+/a11ytests/lockbutton.txt
/usr/libexec/installed-tests/gtk+/a11ytests/lockbutton.ui
/usr/libexec/installed-tests/gtk+/a11ytests/menu.txt
/usr/libexec/installed-tests/gtk+/a11ytests/menu.ui
/usr/libexec/installed-tests/gtk+/a11ytests/menubutton.txt
/usr/libexec/installed-tests/gtk+/a11ytests/menubutton.ui
/usr/libexec/installed-tests/gtk+/a11ytests/menubutton2.txt
/usr/libexec/installed-tests/gtk+/a11ytests/menubutton2.ui
/usr/libexec/installed-tests/gtk+/a11ytests/menubutton3.txt
/usr/libexec/installed-tests/gtk+/a11ytests/menubutton3.ui
/usr/libexec/installed-tests/gtk+/a11ytests/messagedialog.txt
/usr/libexec/installed-tests/gtk+/a11ytests/messagedialog.ui
/usr/libexec/installed-tests/gtk+/a11ytests/mnemonic.txt
/usr/libexec/installed-tests/gtk+/a11ytests/mnemonic.ui
/usr/libexec/installed-tests/gtk+/a11ytests/notebook.txt
/usr/libexec/installed-tests/gtk+/a11ytests/notebook.ui
/usr/libexec/installed-tests/gtk+/a11ytests/paned.txt
/usr/libexec/installed-tests/gtk+/a11ytests/paned.ui
/usr/libexec/installed-tests/gtk+/a11ytests/pickers.txt
/usr/libexec/installed-tests/gtk+/a11ytests/pickers.ui
/usr/libexec/installed-tests/gtk+/a11ytests/placeholder-text.txt
/usr/libexec/installed-tests/gtk+/a11ytests/placeholder-text.ui
/usr/libexec/installed-tests/gtk+/a11ytests/progress.txt
/usr/libexec/installed-tests/gtk+/a11ytests/progress.ui
/usr/libexec/installed-tests/gtk+/a11ytests/range.txt
/usr/libexec/installed-tests/gtk+/a11ytests/range.ui
/usr/libexec/installed-tests/gtk+/a11ytests/scale-drawvalue.txt
/usr/libexec/installed-tests/gtk+/a11ytests/scale-drawvalue.ui
/usr/libexec/installed-tests/gtk+/a11ytests/spinner.txt
/usr/libexec/installed-tests/gtk+/a11ytests/spinner.ui
/usr/libexec/installed-tests/gtk+/a11ytests/stack.txt
/usr/libexec/installed-tests/gtk+/a11ytests/stack.ui
/usr/libexec/installed-tests/gtk+/a11ytests/statusbar.txt
/usr/libexec/installed-tests/gtk+/a11ytests/statusbar.ui
/usr/libexec/installed-tests/gtk+/a11ytests/text.txt
/usr/libexec/installed-tests/gtk+/a11ytests/text.ui
/usr/libexec/installed-tests/gtk+/a11ytests/tooltips.txt
/usr/libexec/installed-tests/gtk+/a11ytests/tooltips.ui
/usr/libexec/installed-tests/gtk+/a11ytests/tree.txt
/usr/libexec/installed-tests/gtk+/a11ytests/tree.ui
/usr/libexec/installed-tests/gtk+/accel
/usr/libexec/installed-tests/gtk+/accessibility-dump
/usr/libexec/installed-tests/gtk+/accessible
/usr/libexec/installed-tests/gtk+/action
/usr/libexec/installed-tests/gtk+/adjustment
/usr/libexec/installed-tests/gtk+/autotestkeywords
/usr/libexec/installed-tests/gtk+/bitmask
/usr/libexec/installed-tests/gtk+/builder
/usr/libexec/installed-tests/gtk+/builderparser
/usr/libexec/installed-tests/gtk+/cairo
/usr/libexec/installed-tests/gtk+/cellarea
/usr/libexec/installed-tests/gtk+/check-cursor-names
/usr/libexec/installed-tests/gtk+/check-icon-names
/usr/libexec/installed-tests/gtk+/children
/usr/libexec/installed-tests/gtk+/clipboard
/usr/libexec/installed-tests/gtk+/css/api
/usr/libexec/installed-tests/gtk+/css/nodes/box-packing.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/box-packing.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/box-packing.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/box-packing.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/box.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/box.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/box.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/box.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/buttons.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/buttons.ui
/usr/libexec/installed-tests/gtk+/css/nodes/checkbutton.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/checkbutton.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/checkbutton.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/checkbutton.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/combobox.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/combobox.ui
/usr/libexec/installed-tests/gtk+/css/nodes/entries.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/entries.ui
/usr/libexec/installed-tests/gtk+/css/nodes/expander.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/expander.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/expander.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/expander.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/levelbar.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/levelbar.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/levelbar.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/levelbar.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook-arrows.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook-arrows.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook-arrows2.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook-arrows2.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.bottom.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.bottom.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.bottom.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.bottom.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.left.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.left.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.left.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.left.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.right.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.right.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.right.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.right.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.top.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.top.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.top.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/notebook.top.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/paned.ltr.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/paned.ltr.ui
/usr/libexec/installed-tests/gtk+/css/nodes/paned.rtl.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/paned.rtl.ui
/usr/libexec/installed-tests/gtk+/css/nodes/progressbar.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/progressbar.ui
/usr/libexec/installed-tests/gtk+/css/nodes/scale.nodes
/usr/libexec/installed-tests/gtk+/css/nodes/scale.ui
/usr/libexec/installed-tests/gtk+/css/nodes/test-css-nodes
/usr/libexec/installed-tests/gtk+/css/parser/animation-crash-3.12.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-crash-3.12.errors
/usr/libexec/installed-tests/gtk+/css/parser/animation-crash-3.12.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-delay.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-delay.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-direction.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-direction.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-duration.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-duration.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-fill-mode.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-fill-mode.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-iteration-count.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-iteration-count.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-name.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-name.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-play-state.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-play-state.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-shorthand-crash.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-shorthand-crash.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-timing-function.css
/usr/libexec/installed-tests/gtk+/css/parser/animation-timing-function.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-01.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-01.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-01.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-02.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-02.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-02.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-03.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-03.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-03.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-04.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-04.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-04.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-05.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-05.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-05.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-06.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-06.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-06.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-07.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-07.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-07.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-08.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-08.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-08.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-09.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-09.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-09.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-10.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-10.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-10.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-11.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-11.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-11.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-12.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-12.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-12.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-13.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-13.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-13.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-14.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-14.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-14.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-15.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-15.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-15.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-16.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-16.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-16.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-17.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-17.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-17.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-18.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-18.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-18.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-19.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-19.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-19.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-20.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-20.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-20.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-21.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-21.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-21.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-22.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-22.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-22.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-23.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-23.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-23.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-24.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-24.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-24.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-25.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-25.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-25.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-26.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-26.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-26.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-27.css
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-27.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-invalid-27.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-01.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-01.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-02.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-02.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-03.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-03.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-04.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-04.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-05.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-05.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-06.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-06.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-07.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-08.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-08.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-09.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-09.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-10.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-10.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-11.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-11.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-12.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-12.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-13.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-13.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-14.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-14.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-15.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-15.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-16.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-16.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-17.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-18.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-18.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-19.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-19.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-19.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-20.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-20.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-20.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-21.css
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-21.errors
/usr/libexec/installed-tests/gtk+/css/parser/at-valid-21.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-blend-mode.css
/usr/libexec/installed-tests/gtk+/css/parser/background-blend-mode.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-clip.css
/usr/libexec/installed-tests/gtk+/css/parser/background-clip.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-image.css
/usr/libexec/installed-tests/gtk+/css/parser/background-image.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-origin.css
/usr/libexec/installed-tests/gtk+/css/parser/background-origin.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-position-errors.css
/usr/libexec/installed-tests/gtk+/css/parser/background-position-errors.errors
/usr/libexec/installed-tests/gtk+/css/parser/background-position-errors.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-position.css
/usr/libexec/installed-tests/gtk+/css/parser/background-position.errors
/usr/libexec/installed-tests/gtk+/css/parser/background-position.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-repeat.css
/usr/libexec/installed-tests/gtk+/css/parser/background-repeat.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-shorthand-single.css
/usr/libexec/installed-tests/gtk+/css/parser/background-shorthand-single.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-shorthand.css
/usr/libexec/installed-tests/gtk+/css/parser/background-shorthand.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-size.css
/usr/libexec/installed-tests/gtk+/css/parser/background-size.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/background-win32-color-is-no-error.css
/usr/libexec/installed-tests/gtk+/css/parser/background-win32-color-is-no-error.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-color-currentcolor.css
/usr/libexec/installed-tests/gtk+/css/parser/border-color-currentcolor.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-color.css
/usr/libexec/installed-tests/gtk+/css/parser/border-color.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-crash-3.24.css
/usr/libexec/installed-tests/gtk+/css/parser/border-crash-3.24.errors
/usr/libexec/installed-tests/gtk+/css/parser/border-crash-3.24.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-repeat.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-repeat.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-slice.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-slice.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-source.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-source.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-width.css
/usr/libexec/installed-tests/gtk+/css/parser/border-image-width.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-infloop-3.12.css
/usr/libexec/installed-tests/gtk+/css/parser/border-infloop-3.12.errors
/usr/libexec/installed-tests/gtk+/css/parser/border-infloop-3.12.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-radius-shorthand.css
/usr/libexec/installed-tests/gtk+/css/parser/border-radius-shorthand.errors
/usr/libexec/installed-tests/gtk+/css/parser/border-radius-shorthand.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-radius.css
/usr/libexec/installed-tests/gtk+/css/parser/border-radius.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-shorthand.css
/usr/libexec/installed-tests/gtk+/css/parser/border-shorthand.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-style.css
/usr/libexec/installed-tests/gtk+/css/parser/border-style.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border-width.css
/usr/libexec/installed-tests/gtk+/css/parser/border-width.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/border.css
/usr/libexec/installed-tests/gtk+/css/parser/border.errors
/usr/libexec/installed-tests/gtk+/css/parser/border.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/box-shadow.css
/usr/libexec/installed-tests/gtk+/css/parser/box-shadow.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/calc-errors.css
/usr/libexec/installed-tests/gtk+/css/parser/calc-errors.errors
/usr/libexec/installed-tests/gtk+/css/parser/calc-errors.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/calc-simple.css
/usr/libexec/installed-tests/gtk+/css/parser/calc-simple.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/calc.css
/usr/libexec/installed-tests/gtk+/css/parser/calc.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/close-at-end-of-file.css
/usr/libexec/installed-tests/gtk+/css/parser/close-at-end-of-file.errors
/usr/libexec/installed-tests/gtk+/css/parser/close-at-end-of-file.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/color.css
/usr/libexec/installed-tests/gtk+/css/parser/color.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/colors-errors.css
/usr/libexec/installed-tests/gtk+/css/parser/colors-errors.errors
/usr/libexec/installed-tests/gtk+/css/parser/colors-errors.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/colors-red.css
/usr/libexec/installed-tests/gtk+/css/parser/colors-red.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/comment-detection.css
/usr/libexec/installed-tests/gtk+/css/parser/comment-detection.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/cross-fade-basic.css
/usr/libexec/installed-tests/gtk+/css/parser/css-21-malformed-declarations.css
/usr/libexec/installed-tests/gtk+/css/parser/css-21-malformed-declarations.errors
/usr/libexec/installed-tests/gtk+/css/parser/css-21-malformed-declarations.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/css-21-malformed-statements.css
/usr/libexec/installed-tests/gtk+/css/parser/css-21-malformed-statements.errors
/usr/libexec/installed-tests/gtk+/css/parser/css-21-malformed-statements.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/currentcolor-everywhere.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-01.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-01.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-01.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-02.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-02.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-02.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-03.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-03.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-03.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-04.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-04.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-04.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-05.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-05.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-05.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-06.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-06.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-06.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-07.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-07.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-07.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-08.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-08.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations-invalid-08.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-01.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-01.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-02.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-02.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-03.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-03.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-04.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-04.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-05.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-05.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-06.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-06.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-07.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-07.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-08.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-08.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-09.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-09.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-10.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-10.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-11.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-11.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-12.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-12.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-13.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-13.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-14.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-14.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-15.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-15.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-16.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-16.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-17.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-17.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-18.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-18.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-19.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-19.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-20.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-20.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-21.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-21.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-22.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-22.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-23.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-23.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-24.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-24.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-25.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-25.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-26.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations-valid-26.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations.css
/usr/libexec/installed-tests/gtk+/css/parser/declarations.errors
/usr/libexec/installed-tests/gtk+/css/parser/declarations.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/deprecated.css
/usr/libexec/installed-tests/gtk+/css/parser/deprecated.errors
/usr/libexec/installed-tests/gtk+/css/parser/deprecated.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/does-not-exist.css
/usr/libexec/installed-tests/gtk+/css/parser/does-not-exist.errors
/usr/libexec/installed-tests/gtk+/css/parser/does-not-exist.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/doubled.css
/usr/libexec/installed-tests/gtk+/css/parser/doubled.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/empty.css
/usr/libexec/installed-tests/gtk+/css/parser/font-family.css
/usr/libexec/installed-tests/gtk+/css/parser/font-family.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/font-size.css
/usr/libexec/installed-tests/gtk+/css/parser/font-size.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/font-stretch.css
/usr/libexec/installed-tests/gtk+/css/parser/font-stretch.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/font-style.css
/usr/libexec/installed-tests/gtk+/css/parser/font-style.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/font-variant.css
/usr/libexec/installed-tests/gtk+/css/parser/font-variant.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/font-weight.css
/usr/libexec/installed-tests/gtk+/css/parser/font-weight.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/freed-string-in-error-messages.css
/usr/libexec/installed-tests/gtk+/css/parser/freed-string-in-error-messages.errors
/usr/libexec/installed-tests/gtk+/css/parser/freed-string-in-error-messages.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-1.css
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-1.errors
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-1.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-2.css
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-2.errors
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-2.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-3.css
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-3.errors
/usr/libexec/installed-tests/gtk+/css/parser/import-cyclic-3.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/import-nonexistant.css
/usr/libexec/installed-tests/gtk+/css/parser/import-nonexistant.errors
/usr/libexec/installed-tests/gtk+/css/parser/import-nonexistant.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/import-recursive.css
/usr/libexec/installed-tests/gtk+/css/parser/import-recursive.errors
/usr/libexec/installed-tests/gtk+/css/parser/import-recursive.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/integer.css
/usr/libexec/installed-tests/gtk+/css/parser/integer.errors
/usr/libexec/installed-tests/gtk+/css/parser/integer.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/keyframes-empty.css
/usr/libexec/installed-tests/gtk+/css/parser/keyframes-empty.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/keyframes-ordering.css
/usr/libexec/installed-tests/gtk+/css/parser/keyframes-ordering.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/letter-spacing.css
/usr/libexec/installed-tests/gtk+/css/parser/letter-spacing.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/linear-gradient.css
/usr/libexec/installed-tests/gtk+/css/parser/linear-gradient.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/margin.css
/usr/libexec/installed-tests/gtk+/css/parser/margin.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/min-height.css
/usr/libexec/installed-tests/gtk+/css/parser/min-height.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/min-width.css
/usr/libexec/installed-tests/gtk+/css/parser/min-width.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/no-semicolon.css
/usr/libexec/installed-tests/gtk+/css/parser/no-semicolon.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/not.css
/usr/libexec/installed-tests/gtk+/css/parser/not.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/nth-child.css
/usr/libexec/installed-tests/gtk+/css/parser/nth-child.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/opacity.css
/usr/libexec/installed-tests/gtk+/css/parser/opacity.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-color.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-color.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-offset.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-offset.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-radius.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-radius.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-style.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-style.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-width.css
/usr/libexec/installed-tests/gtk+/css/parser/outline-width.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/padding.css
/usr/libexec/installed-tests/gtk+/css/parser/padding.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/property-name-errors.css
/usr/libexec/installed-tests/gtk+/css/parser/property-name-errors.errors
/usr/libexec/installed-tests/gtk+/css/parser/property-name-errors.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/pseudo-classes-known.css
/usr/libexec/installed-tests/gtk+/css/parser/pseudo-classes-known.errors
/usr/libexec/installed-tests/gtk+/css/parser/pseudo-classes-known.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/pseudo-classes-unknown.css
/usr/libexec/installed-tests/gtk+/css/parser/pseudo-classes-unknown.errors
/usr/libexec/installed-tests/gtk+/css/parser/pseudo-classes-unknown.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/radial-background-position-error.css
/usr/libexec/installed-tests/gtk+/css/parser/radial-background-position-error.errors
/usr/libexec/installed-tests/gtk+/css/parser/radial-background-position-error.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/radial-positions.css
/usr/libexec/installed-tests/gtk+/css/parser/radial-positions.errors
/usr/libexec/installed-tests/gtk+/css/parser/radial-positions.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/radial.css
/usr/libexec/installed-tests/gtk+/css/parser/radial.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/selector.css
/usr/libexec/installed-tests/gtk+/css/parser/selector.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/shadow.css
/usr/libexec/installed-tests/gtk+/css/parser/shadow.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/shorthand.css
/usr/libexec/installed-tests/gtk+/css/parser/shorthand.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/simple.css
/usr/libexec/installed-tests/gtk+/css/parser/single-slash.css
/usr/libexec/installed-tests/gtk+/css/parser/single-slash.errors
/usr/libexec/installed-tests/gtk+/css/parser/single-slash.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/string-values.css
/usr/libexec/installed-tests/gtk+/css/parser/string-values.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/test-css-parser
/usr/libexec/installed-tests/gtk+/css/parser/test.png
/usr/libexec/installed-tests/gtk+/css/parser/text-decoration-color.css
/usr/libexec/installed-tests/gtk+/css/parser/text-decoration-color.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/text-decoration-line.css
/usr/libexec/installed-tests/gtk+/css/parser/text-decoration-line.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/text-decoration-style.css
/usr/libexec/installed-tests/gtk+/css/parser/text-decoration-style.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/text-shadow-invalid-but-worked-in-3.12.css
/usr/libexec/installed-tests/gtk+/css/parser/text-shadow-invalid-but-worked-in-3.12.errors
/usr/libexec/installed-tests/gtk+/css/parser/text-shadow-invalid-but-worked-in-3.12.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/text-shadow.css
/usr/libexec/installed-tests/gtk+/css/parser/text-shadow.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-delay.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-delay.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-duration.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-duration.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-property.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-property.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-timing-function.css
/usr/libexec/installed-tests/gtk+/css/parser/transition-timing-function.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/transition.css
/usr/libexec/installed-tests/gtk+/css/parser/transition.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/value-inherit-shorthand.css
/usr/libexec/installed-tests/gtk+/css/parser/value-inherit-shorthand.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/value-inherit.css
/usr/libexec/installed-tests/gtk+/css/parser/value-inherit.errors
/usr/libexec/installed-tests/gtk+/css/parser/value-initial-shorthand.css
/usr/libexec/installed-tests/gtk+/css/parser/value-initial-shorthand.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/value-initial.css
/usr/libexec/installed-tests/gtk+/css/parser/value-initial.errors
/usr/libexec/installed-tests/gtk+/css/parser/value-none.css
/usr/libexec/installed-tests/gtk+/css/parser/value-none.errors
/usr/libexec/installed-tests/gtk+/css/parser/value-none.ref.css
/usr/libexec/installed-tests/gtk+/css/parser/widget-style-property.css
/usr/libexec/installed-tests/gtk+/css/style/adjacent-states.css
/usr/libexec/installed-tests/gtk+/css/style/adjacent-states.nodes
/usr/libexec/installed-tests/gtk+/css/style/adjacent-states.ui
/usr/libexec/installed-tests/gtk+/css/style/colornames.css
/usr/libexec/installed-tests/gtk+/css/style/colornames.nodes
/usr/libexec/installed-tests/gtk+/css/style/colornames.ui
/usr/libexec/installed-tests/gtk+/css/style/currentcolor.css
/usr/libexec/installed-tests/gtk+/css/style/currentcolor.nodes
/usr/libexec/installed-tests/gtk+/css/style/currentcolor.ui
/usr/libexec/installed-tests/gtk+/css/style/font.css
/usr/libexec/installed-tests/gtk+/css/style/font.nodes
/usr/libexec/installed-tests/gtk+/css/style/font.ui
/usr/libexec/installed-tests/gtk+/css/style/gradient.css
/usr/libexec/installed-tests/gtk+/css/style/gradient.nodes
/usr/libexec/installed-tests/gtk+/css/style/gradient.ui
/usr/libexec/installed-tests/gtk+/css/style/inherit.css
/usr/libexec/installed-tests/gtk+/css/style/inherit.nodes
/usr/libexec/installed-tests/gtk+/css/style/inherit.ui
/usr/libexec/installed-tests/gtk+/css/style/label.css
/usr/libexec/installed-tests/gtk+/css/style/label.nodes
/usr/libexec/installed-tests/gtk+/css/style/label.ui
/usr/libexec/installed-tests/gtk+/css/style/nth-child.css
/usr/libexec/installed-tests/gtk+/css/style/nth-child.nodes
/usr/libexec/installed-tests/gtk+/css/style/nth-child.ui
/usr/libexec/installed-tests/gtk+/css/style/test-css-style
/usr/libexec/installed-tests/gtk+/cssprovider
/usr/libexec/installed-tests/gtk+/defaultvalue
/usr/libexec/installed-tests/gtk+/derive
/usr/libexec/installed-tests/gtk+/display
/usr/libexec/installed-tests/gtk+/displayclose
/usr/libexec/installed-tests/gtk+/encoding
/usr/libexec/installed-tests/gtk+/entry
/usr/libexec/installed-tests/gtk+/firefox-stylecontext
/usr/libexec/installed-tests/gtk+/floating
/usr/libexec/installed-tests/gtk+/focus
/usr/libexec/installed-tests/gtk+/gestures
/usr/libexec/installed-tests/gtk+/grid
/usr/libexec/installed-tests/gtk+/gtkmenu
/usr/libexec/installed-tests/gtk+/icons/15/size-test.png
/usr/libexec/installed-tests/gtk+/icons/16-22/size-test.png
/usr/libexec/installed-tests/gtk+/icons/16x16/simple.png
/usr/libexec/installed-tests/gtk+/icons/16x16/twosize-fixed.svg
/usr/libexec/installed-tests/gtk+/icons/16x16s/twosize.svg
/usr/libexec/installed-tests/gtk+/icons/25+/size-test.svg
/usr/libexec/installed-tests/gtk+/icons/32x32/only32-symbolic.svg
/usr/libexec/installed-tests/gtk+/icons/32x32/twosize-fixed.svg
/usr/libexec/installed-tests/gtk+/icons/32x32s/twosize.svg
/usr/libexec/installed-tests/gtk+/icons/35+/size-test.svg
/usr/libexec/installed-tests/gtk+/icons/index.theme
/usr/libexec/installed-tests/gtk+/icons/scalable/everything-justregular.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/everything-justrtl-rtl.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/everything-justsymbolic-symbolic.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/everything-rtl.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/everything-symbolic-rtl.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/everything-symbolic.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/everything.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/nonsquare-symbolic.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/one-two-rtl.svg
/usr/libexec/installed-tests/gtk+/icons/scalable/one-two.svg
/usr/libexec/installed-tests/gtk+/icons2/index.theme
/usr/libexec/installed-tests/gtk+/icons2/scalable/one-two-symbolic-rtl.svg
/usr/libexec/installed-tests/gtk+/icons2/scalable/one-two-symbolic.svg
/usr/libexec/installed-tests/gtk+/icons2/scalable/one-two-three-symbolic.svg
/usr/libexec/installed-tests/gtk+/icontheme
/usr/libexec/installed-tests/gtk+/keyhash
/usr/libexec/installed-tests/gtk+/keysyms
/usr/libexec/installed-tests/gtk+/listbox
/usr/libexec/installed-tests/gtk+/misc
/usr/libexec/installed-tests/gtk+/no-gtk-init
/usr/libexec/installed-tests/gtk+/notify
/usr/libexec/installed-tests/gtk+/object
/usr/libexec/installed-tests/gtk+/objects-finalize
/usr/libexec/installed-tests/gtk+/papersize
/usr/libexec/installed-tests/gtk+/rbtree
/usr/libexec/installed-tests/gtk+/recentmanager
/usr/libexec/installed-tests/gtk+/rectangle
/usr/libexec/installed-tests/gtk+/regression-tests
/usr/libexec/installed-tests/gtk+/revealer-size
/usr/libexec/installed-tests/gtk+/rgba
/usr/libexec/installed-tests/gtk+/scrolledwindow
/usr/libexec/installed-tests/gtk+/seat
/usr/libexec/installed-tests/gtk+/simplify/test1.expected
/usr/libexec/installed-tests/gtk+/simplify/test1.ui
/usr/libexec/installed-tests/gtk+/simplify/test2.expected
/usr/libexec/installed-tests/gtk+/simplify/test2.ui
/usr/libexec/installed-tests/gtk+/simplify/test3.expected
/usr/libexec/installed-tests/gtk+/simplify/test3.ui
/usr/libexec/installed-tests/gtk+/simplify/test4.expected
/usr/libexec/installed-tests/gtk+/simplify/test4.ui
/usr/libexec/installed-tests/gtk+/simplify/test5.expected
/usr/libexec/installed-tests/gtk+/simplify/test5.ui
/usr/libexec/installed-tests/gtk+/simplify/test6.expected
/usr/libexec/installed-tests/gtk+/simplify/test6.ui
/usr/libexec/installed-tests/gtk+/simplify/test7.expected
/usr/libexec/installed-tests/gtk+/simplify/test7.ui
/usr/libexec/installed-tests/gtk+/simplify/test8.expected
/usr/libexec/installed-tests/gtk+/simplify/test8.ui
/usr/libexec/installed-tests/gtk+/spinbutton
/usr/libexec/installed-tests/gtk+/state-record
/usr/libexec/installed-tests/gtk+/state/focus1.in
/usr/libexec/installed-tests/gtk+/state/focus1.out
/usr/libexec/installed-tests/gtk+/state/focus1.ui
/usr/libexec/installed-tests/gtk+/state/focus2.in
/usr/libexec/installed-tests/gtk+/state/focus2.out
/usr/libexec/installed-tests/gtk+/state/focus2.ui
/usr/libexec/installed-tests/gtk+/stylecontext
/usr/libexec/installed-tests/gtk+/templates
/usr/libexec/installed-tests/gtk+/test-settings
/usr/libexec/installed-tests/gtk+/test-simplify
/usr/libexec/installed-tests/gtk+/text
/usr/libexec/installed-tests/gtk+/textbuffer
/usr/libexec/installed-tests/gtk+/textiter
/usr/libexec/installed-tests/gtk+/tree-performance
/usr/libexec/installed-tests/gtk+/tree-relationships
/usr/libexec/installed-tests/gtk+/treemodel
/usr/libexec/installed-tests/gtk+/treepath
/usr/libexec/installed-tests/gtk+/treeview
/usr/libexec/installed-tests/gtk+/typename
/usr/libexec/installed-tests/gtk+/ui/celllayout1.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout1.ui
/usr/libexec/installed-tests/gtk+/ui/celllayout2.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout2.ui
/usr/libexec/installed-tests/gtk+/ui/celllayout3.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout3.ui
/usr/libexec/installed-tests/gtk+/ui/celllayout4.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout4.ui
/usr/libexec/installed-tests/gtk+/ui/celllayout5.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout5.ui
/usr/libexec/installed-tests/gtk+/ui/celllayout6.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout6.ui
/usr/libexec/installed-tests/gtk+/ui/celllayout7.expected
/usr/libexec/installed-tests/gtk+/ui/celllayout7.ui
/usr/libexec/installed-tests/gtk+/ui/container1.expected
/usr/libexec/installed-tests/gtk+/ui/container1.ui
/usr/libexec/installed-tests/gtk+/ui/container2.expected
/usr/libexec/installed-tests/gtk+/ui/container2.ui
/usr/libexec/installed-tests/gtk+/ui/container3.expected
/usr/libexec/installed-tests/gtk+/ui/container3.ui
/usr/libexec/installed-tests/gtk+/ui/container4.expected
/usr/libexec/installed-tests/gtk+/ui/container4.ui
/usr/libexec/installed-tests/gtk+/ui/container5.expected
/usr/libexec/installed-tests/gtk+/ui/container5.ui
/usr/libexec/installed-tests/gtk+/ui/container6.expected
/usr/libexec/installed-tests/gtk+/ui/container6.ui
/usr/libexec/installed-tests/gtk+/ui/container7.expected
/usr/libexec/installed-tests/gtk+/ui/container7.ui
/usr/libexec/installed-tests/gtk+/ui/container8.expected
/usr/libexec/installed-tests/gtk+/ui/container8.ui
/usr/libexec/installed-tests/gtk+/ui/dialog1.expected
/usr/libexec/installed-tests/gtk+/ui/dialog1.ui
/usr/libexec/installed-tests/gtk+/ui/dialog2.expected
/usr/libexec/installed-tests/gtk+/ui/dialog2.ui
/usr/libexec/installed-tests/gtk+/ui/dialog3.expected
/usr/libexec/installed-tests/gtk+/ui/dialog3.ui
/usr/libexec/installed-tests/gtk+/ui/dialog4.expected
/usr/libexec/installed-tests/gtk+/ui/dialog4.ui
/usr/libexec/installed-tests/gtk+/ui/dialog5.expected
/usr/libexec/installed-tests/gtk+/ui/dialog5.ui
/usr/libexec/installed-tests/gtk+/ui/dialog6.expected
/usr/libexec/installed-tests/gtk+/ui/dialog6.ui
/usr/libexec/installed-tests/gtk+/ui/dialog7.expected
/usr/libexec/installed-tests/gtk+/ui/dialog7.ui
/usr/libexec/installed-tests/gtk+/ui/dialog8.expected
/usr/libexec/installed-tests/gtk+/ui/dialog8.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter1.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter1.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter10.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter10.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter2.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter2.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter3.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter3.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter4.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter4.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter5.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter5.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter6.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter6.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter7.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter7.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter8.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter8.ui
/usr/libexec/installed-tests/gtk+/ui/filefilter9.expected
/usr/libexec/installed-tests/gtk+/ui/filefilter9.ui
/usr/libexec/installed-tests/gtk+/ui/image1.expected
/usr/libexec/installed-tests/gtk+/ui/image1.ui
/usr/libexec/installed-tests/gtk+/ui/image2.expected
/usr/libexec/installed-tests/gtk+/ui/image2.ui
/usr/libexec/installed-tests/gtk+/ui/infobar1.expected
/usr/libexec/installed-tests/gtk+/ui/infobar1.ui
/usr/libexec/installed-tests/gtk+/ui/infobar2.expected
/usr/libexec/installed-tests/gtk+/ui/infobar2.ui
/usr/libexec/installed-tests/gtk+/ui/infobar3.expected
/usr/libexec/installed-tests/gtk+/ui/infobar3.ui
/usr/libexec/installed-tests/gtk+/ui/infobar4.expected
/usr/libexec/installed-tests/gtk+/ui/infobar4.ui
/usr/libexec/installed-tests/gtk+/ui/infobar5.expected
/usr/libexec/installed-tests/gtk+/ui/infobar5.ui
/usr/libexec/installed-tests/gtk+/ui/infobar6.expected
/usr/libexec/installed-tests/gtk+/ui/infobar6.ui
/usr/libexec/installed-tests/gtk+/ui/label1.expected
/usr/libexec/installed-tests/gtk+/ui/label1.ui
/usr/libexec/installed-tests/gtk+/ui/label2.expected
/usr/libexec/installed-tests/gtk+/ui/label2.ui
/usr/libexec/installed-tests/gtk+/ui/label3.expected
/usr/libexec/installed-tests/gtk+/ui/label3.ui
/usr/libexec/installed-tests/gtk+/ui/label4.expected
/usr/libexec/installed-tests/gtk+/ui/label4.ui
/usr/libexec/installed-tests/gtk+/ui/label5.expected
/usr/libexec/installed-tests/gtk+/ui/label5.ui
/usr/libexec/installed-tests/gtk+/ui/levelbar1.expected
/usr/libexec/installed-tests/gtk+/ui/levelbar1.ui
/usr/libexec/installed-tests/gtk+/ui/levelbar2.expected
/usr/libexec/installed-tests/gtk+/ui/levelbar2.ui
/usr/libexec/installed-tests/gtk+/ui/levelbar3.expected
/usr/libexec/installed-tests/gtk+/ui/levelbar3.ui
/usr/libexec/installed-tests/gtk+/ui/levelbar4.expected
/usr/libexec/installed-tests/gtk+/ui/levelbar4.ui
/usr/libexec/installed-tests/gtk+/ui/levelbar5.expected
/usr/libexec/installed-tests/gtk+/ui/levelbar5.ui
/usr/libexec/installed-tests/gtk+/ui/levelbar6.expected
/usr/libexec/installed-tests/gtk+/ui/levelbar6.ui
/usr/libexec/installed-tests/gtk+/ui/scale1.expected
/usr/libexec/installed-tests/gtk+/ui/scale1.ui
/usr/libexec/installed-tests/gtk+/ui/scale2.expected
/usr/libexec/installed-tests/gtk+/ui/scale2.ui
/usr/libexec/installed-tests/gtk+/ui/scale3.expected
/usr/libexec/installed-tests/gtk+/ui/scale3.ui
/usr/libexec/installed-tests/gtk+/ui/scale4.expected
/usr/libexec/installed-tests/gtk+/ui/scale4.ui
/usr/libexec/installed-tests/gtk+/ui/scale5.expected
/usr/libexec/installed-tests/gtk+/ui/scale5.ui
/usr/libexec/installed-tests/gtk+/ui/scale6.expected
/usr/libexec/installed-tests/gtk+/ui/scale6.ui
/usr/libexec/installed-tests/gtk+/ui/scale7.expected
/usr/libexec/installed-tests/gtk+/ui/scale7.ui
/usr/libexec/installed-tests/gtk+/ui/test1.expected
/usr/libexec/installed-tests/gtk+/ui/test1.ui
/usr/libexec/installed-tests/gtk+/ui/test2.expected
/usr/libexec/installed-tests/gtk+/ui/test2.ui
/usr/libexec/installed-tests/gtk+/ui/test3.expected
/usr/libexec/installed-tests/gtk+/ui/test3.ui
/usr/libexec/installed-tests/gtk+/ui/test4.expected
/usr/libexec/installed-tests/gtk+/ui/test4.ui
/usr/libexec/installed-tests/gtk+/ui/test5.expected
/usr/libexec/installed-tests/gtk+/ui/test5.ui
/usr/libexec/installed-tests/gtk+/ui/test6.expected
/usr/libexec/installed-tests/gtk+/ui/test6.ui
/usr/libexec/installed-tests/gtk+/ui/test7.expected
/usr/libexec/installed-tests/gtk+/ui/test7.ui
/usr/libexec/installed-tests/gtk+/util
/usr/libexec/installed-tests/gtk+/value
/usr/libexec/installed-tests/gtk+/visual
/usr/libexec/installed-tests/gtk+/window
/usr/share/clear/optimized-elf/test*
/usr/share/installed-tests/gtk+/a11ychildren.test
/usr/share/installed-tests/gtk+/a11yderive.test
/usr/share/installed-tests/gtk+/a11ymisc.test
/usr/share/installed-tests/gtk+/a11ytext.test
/usr/share/installed-tests/gtk+/a11ytree.test
/usr/share/installed-tests/gtk+/a11yutil.test
/usr/share/installed-tests/gtk+/a11yvalue.test
/usr/share/installed-tests/gtk+/accel.test
/usr/share/installed-tests/gtk+/accessible.test
/usr/share/installed-tests/gtk+/action.test
/usr/share/installed-tests/gtk+/adjustment.test
/usr/share/installed-tests/gtk+/autotestkeywords.test
/usr/share/installed-tests/gtk+/bitmask.test
/usr/share/installed-tests/gtk+/builder.test
/usr/share/installed-tests/gtk+/builderparser.test
/usr/share/installed-tests/gtk+/cellarea.test
/usr/share/installed-tests/gtk+/check-cursor-names.test
/usr/share/installed-tests/gtk+/check-icon-names.test
/usr/share/installed-tests/gtk+/clipboard.test
/usr/share/installed-tests/gtk+/css/api.test
/usr/share/installed-tests/gtk+/css/nodes/test-css-nodes.test
/usr/share/installed-tests/gtk+/css/parser/test-css-parser.test
/usr/share/installed-tests/gtk+/css/style/test-css-style.test
/usr/share/installed-tests/gtk+/cssprovider.test
/usr/share/installed-tests/gtk+/defaultvalue.test
/usr/share/installed-tests/gtk+/displayclose.test
/usr/share/installed-tests/gtk+/entry.test
/usr/share/installed-tests/gtk+/firefox-stylecontext.test
/usr/share/installed-tests/gtk+/floating.test
/usr/share/installed-tests/gtk+/focus.test
/usr/share/installed-tests/gtk+/gestures.test
/usr/share/installed-tests/gtk+/grid.test
/usr/share/installed-tests/gtk+/gtkmenu.test
/usr/share/installed-tests/gtk+/icontheme.test
/usr/share/installed-tests/gtk+/keyhash.test
/usr/share/installed-tests/gtk+/listbox.test
/usr/share/installed-tests/gtk+/no-gtk-init.test
/usr/share/installed-tests/gtk+/notify.test
/usr/share/installed-tests/gtk+/object.test
/usr/share/installed-tests/gtk+/objects-finalize.test
/usr/share/installed-tests/gtk+/papersize.test
/usr/share/installed-tests/gtk+/rbtree.test
/usr/share/installed-tests/gtk+/recentmanager.test
/usr/share/installed-tests/gtk+/regression-tests.test
/usr/share/installed-tests/gtk+/revealer-size.test
/usr/share/installed-tests/gtk+/scrolledwindow.test
/usr/share/installed-tests/gtk+/spinbutton.test
/usr/share/installed-tests/gtk+/stylecontext.test
/usr/share/installed-tests/gtk+/templates.test
/usr/share/installed-tests/gtk+/test-settings.test
/usr/share/installed-tests/gtk+/test-simplify.test
/usr/share/installed-tests/gtk+/textbuffer.test
/usr/share/installed-tests/gtk+/textiter.test
/usr/share/installed-tests/gtk+/treemodel.test
/usr/share/installed-tests/gtk+/treepath.test
/usr/share/installed-tests/gtk+/treeview.test
/usr/share/installed-tests/gtk+/typename.test
/usr/share/installed-tests/gtk+/window.test

%files locales -f gtk30-properties.lang -f gtk30.lang
%defattr(-,root,root,-)

